### ISSUE TITLE
checkstyle Error

### ISSUE THREAD

**Issue by EhYongE** [nus-cs2030/2324-s2#103]
# Summary
I keep getting checkstyle error only for few files

## Description 
I did try to redownload .virmc and rewrite the entire code, but I still get the same error.
I did not have this issue with my Lab 1.
For my Lab 2, out of 13 *.java file, only 3 of them are having this issue. 
Does anyone have any idea on how to fix this??

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/88820796/07cf6bf7-9d49-41fe-b372-554a0476fc9f)

**Comment by AustinKong** [comment]
Looks to me that your lines have tabs instead of spaces, and uses 8 spaces instead of 4. Maybe try editing your .vimrc file according to [this link](https://stackoverflow.com/questions/234564/tab-key-4-spaces-and-auto-indent-after-curly-braces-in-vim#:~:text=Within%20Vim%2C%20type%20a%20colon,have%20to%20type%20them%20once.).
