### ISSUE TITLE
Wait... how to do a queue without an ImList or a PQ?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#105]
# Summary

Stuck wondering how the lab TAs suggested this.

## Description:

Still figuring out how to overhaul my queuing logic to simulate a queue effectively, without using a PriorityQueue or a Immutable List.

If I really can't, does that mean that I will have to rewrite my code totally from scratch?

## Screenshots

![image](https://github.com/nus-cs2030/2324-s2/assets/140680858/6fdf4ca6-b2f3-43c7-9094-e114656067a4)

**Comment by samuelneo** [comment]
you shouldn't need to rewrite your code from scratch because of this

consider what information each `Server` needs to know about its queue. is it necessary to have a collection of `Wait` events? can you handle the management of the queue outside `Server`?

in any case, you don't need to adhere to the hint, using an `ImList` to manage the queue is not banned (as long as you can avoid cyclic dependencies)

**Comment by ZHD1987E** [comment]
Hmm…

does that mean using a PQ to manage Wait events is banned?

**Comment by samuelneo** [comment]
no

**Comment by ZHD1987E** [comment]
Fair, will see how my code will implement a queue…

did a draft on the lab itself, turned out that it only supported one person in the queue. Now I have to scrap the entire thing and rebuild from scratch.

**Comment by ZHD1987E** [comment]
Never mind, figured out how thanks to someone who did an earlier iteration of this mod.

1: Queue Event was born
2: Queue Event sees if server can serve them.
3: Yes? Become Serve Event.
4: No? It dies, reincarnates as some other event that will not be logged.
5: So long that the server rejects the queue event just like me having to reject anyone trying to date with me, it will just reincarnate as itself (but time is updated of course!)
6: Inevitable it will be reborn as a Serve Event. Yay.
