### ISSUE TITLE
Lecture 5 Doubts

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#113]
# Description

How can encapsulation be preserved while using optionals internally?

## Topic:

Not breaking encapsulation while using optionals.

## Screenshots

Screenshots (if any)

**Comment by chinwn** [comment]
Could you elaborate more on your question?

Optional<T> is used to add an empty outcome to the T domain, that can be used when we are unable to compute a proper value of type T.

null is not a valid value of the T domain, but instead belongs to the NULL type which is just above the ERROR \bot domains. Thus, if you are unable to compute a value of type T, one should either use an exception to signify an error, or use empty outcome of Optional<T>. Always, avoid null value since the error outcome would only be noticable (as a side effect) when you try to perform method dereferencing on a null object.
