### ISSUE TITLE
L1 Q1 Q2:  Value and expression 

### ISSUE THREAD

**Issue by Wang-Chuhao** [nus-cs2030/2324-s2#12]
Q1: A value is an evaluation of an expression. What makes up an expression?
Q2: What are the three things we can we do to a value in a program? A value can be...

My 2 cents:
For Q1 an expression as I have seen in maths and programming is a combination of values and operators. It's interesting that an expression also evaluates to a value, if the expression is grammatically correct.
For Q2 I learnt that a value can be assigned to a variable, operated by an operator, and passed as input to a method (function).

**Comment by hwkchia** [comment]
Your answers revolve around math, with operations and operands.  But that is a good starting point.
What if a value is `Point`?  There are no operations that operate on `Point` values?

**Comment by cth06-Github** [comment]
Q1 A value is an evaluation of an expression. What makes up an expression?
Responding to/adding on to Prof Chia @hwkchia and Chuhao @Wang-Chuhao :

Initially, I think an expression is anything that does something. For math operands, we are evaluating to obtain a value. `a = 5` that's assigning a value to a variable. I would think that functions are a form of expression.
But I read this that mentioned about declaration vs initialisation vs expression vs statement: [](https://stackoverflow.com/questions/46375122/is-variable-assignment-a-statement-or-expression)

Assuming it makes sense, It gets confusing because it seems like just a few minute differences in syntax and we classify them as different things. For example, it wrote that `x = 5` is an expression but `x = 5;` is a statement. (to be honest, why so particular?).

I think We can always define operations for `Point` class values. For example, we can define what it means to `PointA + PointB`. (Operator overloading). Probably that's why when number adds together with a plus sign, it evaluates a value but when strings are added together with a plus sign, it means string concatenation.

Post script: Wait...Java does not support operator overloading except the "+" sign, according to this article:
https://www.scaler.com/topics/operator-overloading-in-java/
[I was writing the operator overloading response in the context of C++ language]
Nonetheless, I feel that we can think operators as functions. So operators like "+", "-" signs are essentially just functions, or methods. For example, I think in python, the add method associated to integer object is named as `__add__(self, value, /)`.
Thus, we can define methods for Point class to allow for adding, substracting, etc by defining methods.

**Comment by hwkchia** [comment]
To answer @cth06-Github, we know that an expression evaluates to a value.  So `x + 5` evaluates to 5, and `x = 5` also evaluates to 5.  We also know that a value can be assigned to a variable (this is one of the things we can do to a value).  

So `y = (x + 5)` is possible.  

Which means `y = (x = 5)` is also possible.  This assigns both `x` and `y` to `5.`  Defining `x = 5` as an expression is important to allow this.  But this is seldom used, and indeed, makes the program difficult to read (so please don't do this).

On the other hand, a *statement* is different from an *expression*.  Other statements include, `if..else` statement, the `for` statement, etc.  A method with its method head and body is also a statement.  But we are starting to digress...

Coming back to the *three things*.  We already have one above (**a value can be assigned to a variable**). @Wang-Chuhao also provided one more (**a value can be passed as input to a method**).  One more?  Think of what we can do to a `Point`?

**Comment by AvaZard** [comment]
Adding on to this discussion for Q1: A value is an evaluation of an expression. What makes up an expression?

As mentioned by @Wang-Chuhao, @cth06-Github  and Prof, arithmetic expressions are a subset of expressions that can be evaluated and can hence be assigned and passed as input to a method.

My thoughts: How about logical expressions that involve logical operators or expressions that are comparisons? For example boolean isGreatest = (a > b) && (a > c);

Such expressions can be evaluated and would give us a value, as given in the definition in Q1. 


Regarding Q2: What are the three things we can we do to a value in a program? A value can be...

As mentioned by Prof, a value can be assigned to statements and passed as input into methods. Thinking from the perspective of how two different Point values give us output because of their different values as in distanceTo and angleTo, could we say that another property of a value is that it can be compared to other values? Or should we be approaching this question from another angle?

**Comment by chongshaohong** [comment]
> Coming back to the _three things_. We already have one above (**a value can be assigned to a variable**). @Wang-Chuhao also provided one more (**a value can be passed as input to a method**). One more? Think of what we can do to a `Point`?

We can also unassign a value from a variable. For example, when we do
`Point point = new Point(1,1);
point = point.moveTo(2,2);`

The original Point object is unlinked from the "point" reference variable.

**Comment by hwkchia** [comment]
> Regarding Q2: What are the three things we can we do to a value in a program? A value can be...
> 
> As mentioned by Prof, a value can be assigned to statements and passed as input into methods. Thinking from the perspective of how two different Point values give us output because of their different values as in distanceTo and angleTo, could we say that another property of a value is that it can be compared to other values? Or should we be approaching this question from another angle?

Not all values can be compared "natively" though.  For example, two objects of a `Circle` class cannot be compared unless there is a method defined to perform the comparison.

Let me give a hint for what I'm looking for.  We already have a value can be passed **to** a method.  What remains is

A value can be ??? **from** a method.

**Comment by hwkchia** [comment]
Expired.
