### ISSUE TITLE
Self Exercise 4 ToString() Issue

### ISSUE THREAD

**Issue by cyting01** [nus-cs2030/2324-s2#128]
Tried my code in jshell and it passes all the testcases, but when I submit it the autograder gives me this error.

![image](https://github.com/nus-cs2030/2324-s2/assets/153883538/31cd64e5-c0a3-4754-b2ac-e6bdcb7ce4eb)

I think it might have something to do with the ToString method required for us in the test cases? Such as 
![image](https://github.com/nus-cs2030/2324-s2/assets/153883538/9a9a3bdd-54b2-42f6-a61b-a93900df6a36)

I tried editing my toString method bodies to not explicitly have "..." inside and codecrunch passes all the testcases now. Just wondering if it's a bug with the autograder. 
![image](https://github.com/nus-cs2030/2324-s2/assets/153883538/a0de5a4a-1b8b-450d-9776-fb57d5ac6d43)

Thank you!

**Comment by cyting01** [comment]
Checked with my TA and they said that I don't even need a toString method because that's the natural output of the object. Me now
![image](https://github.com/nus-cs2030/2324-s2/assets/153883538/17ab26b5-6cb1-44e1-a987-1b40d5375622)

**Comment by samuelneo** [comment]
that `toString()` doesn't need to be overridden. the default output of `toString()` is `ClassName@<memoryaddress>`, with the test cases using ellipses in place of the memory address, since the address is not consistent and doesn't matter

Ellipsis in Java denote [varargs](https://www.geeksforgeeks.org/variable-arguments-varargs-in-java/), and like many other things not covered in CS2030, CodeCrunch bans them, presumably by searching the exact literal `...`
