### ISSUE TITLE
too many service times generated

### ISSUE THREAD

**Issue by itzsihui** [nus-cs2030/2324-s2#130]
# Summary

Description of the question / problem here.
Hii everyone, my outputs are correct inside my mac terminal but when I submit to codecrunch, it seems to throw me the "too many service times generated". may i ask why?

## Description:

Clarifications or details with respect to the issue you are facing

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
<img width="1194" alt="Screenshot 2024-02-26 at 1 10 37 AM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/6aea29cd-4cbf-4f04-ba7c-0c2c65f0edc1">
<img width="540" alt="Screenshot 2024-02-26 at 1 10 50 AM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/67d917cf-e3b0-451c-ad22-82221c223124">

**Comment by LimZiXiong** [comment]
The above test case seems to be 1 server with queue length of 1. Try using the testcase to check. Your program may be serving more customer than intended

1 1
0.500
0.600
0.700

**Comment by codingtemp** [comment]
If your program serves 3 customers, you should only be calling the getServiceTime method 3 times (you should not be calling this on leaving customers). Calling more than 3 times will cause this error. You can try and write print statement on your getServiceTime method to count how many times it is calling, and compare it with the test case to debug.

**Comment by andhika2002** [comment]
From my experience, this issue was resolved in Simulator.java.

 If you have some way to check for what the next event returned is (e.g. when deciding whether to add the event back into your priority queue), consider and note that you are processing the Serve event to return the next event. Each time this checking is performed, getservicetime() would be called because you processed the serve event, calling getServiceTime() in the process. 

Consider processing once only, storing the values, and then checking if they're the same event.

**Comment by jiancheng37** [comment]
you should only call getServiceTime once per customer, any more will result in that error
