### ISSUE TITLE
"equals method invoked via Object type" error on CodeCrunch

### ISSUE THREAD

**Issue by mChewWW** [nus-cs2030/2324-s2#136]
Hi, I'm getting "equals method invoked via Object type" compilation error when submitting lab 3 to code crunch. When testing with VIM, all my code compiles normally and all test cases were successful. The error only occurs when submitting to CC.

I haven't changed/added any new equals method since lab 2, which was submitted successfully and passed all test cases.

The only 2 lines of code I have which invoke any .equals() method is in my Simulator class, and are these 2 lines:
if (!pollData.first().equals(nextEvent.first())) { // if returned event is different
AND
if (!nextEvent.second().equals(serverList)) { // if serverlist was changed

I tried rewriting my code to remove the need for the second and I faced the same error.
I can't remove the first line without having to make significant changes in my code.

I do feel that neither line should be causing the problem since they were present in my successful lab 2 submission.

**Comment by luckrainbow** [comment]
Sounds like you have 2 options to satisfy the checker:
- Use "==" instead.
- Override the equals(Object) method of whatever class is being returned by the Pair.

"==" is probably easier to try first.

-Ethan Goh

**Comment by gnimnix** [comment]
I am guessing your `pollData.first()` is a user defined `Event` object and I am also guessing you have not defined a `equals` method in your `Event` class. Hence, the `equals` method is calling the parent of `Event`, which is `Object` (since all user defined classes inherit from `Object`). The compiler on CodeCrunch detects this and throws this error.

Solution would be to `@Override` the `equals` method in your `Event` class and implement your own logic for comparing two `Event` objects.
