### ISSUE TITLE
L1 Q5: Alternative Representation of Point

### ISSUE THREAD

**Issue by neozemin** [nus-cs2030/2324-s2#14]
Q5: Provide another way to represent the x- and y- coordinates of Point. Modify the distanceTo method so as to make use of this new representation. Will this affect how the client uses Point?

```java
class Point {
      private final double distance;       // distance here refers to the distance from point to origin
      private final double theta;
      Point (double distance, double theta) {
            this.distance = distance;
            this.theta = theta;
      }
      double distanceTo (Point p) {
             double x = this.distance * Math.cos(this.theta) - p.distance * Math.cos(p.theta);
             double y = this.distance * Math.sin(this.theta) - p.distance * Math.sin(p.theta);
             return Math.sqrt(x * x + y * y);
      }
      public String toString() {
             return "(" + this.distance + ", " + this.theta + ")";
      }
}
```
Yes, the client will need to convert all cartesian coordinates to polar coordinates.

**Comment by ZHD1987E** [comment]
But if you are the circle, nothing ever changes. That's why you go use Tell-Don't-Ask: in case someone has a brilliant idea to do an alternative implementation of a dependent class, there is minimal changes except just changing how I input a Point and pass into a Circle.

**Comment by xinweixw** [comment]
This is an interesting way of implementing Point! But, I agree with the above comment. I think how the client creates a point will change (eg inputting distance and theta instead of providing x and y coordinates) but how the client uses the Point class should stay the same. For example, how the method contains(Point point) in the Circle class uses a Point object does not change. The contains(Point point) method uses the distanceTo method from the Point class but Circle does not need to know how distanceTo is implemented, it just needs to know what distanceTo does, hence so long as distanceTo is implemented correctly, the contains(Point point) method should work properly as well.

**Comment by hwkchia** [comment]
Good observations...  If creating a `Point` necessitates taking in two `double` values, then whether the two values specifies $(x,y)$ cartesian coordinates or $(d,\theta)$ polar coordinates must be specified as part of the documentation.

Now suppose we fix it as cartesian coordinates, can the properties of `Point` be only defined with two `double` variables?  That's what the question is asking.

**Comment by LimZiXiong** [comment]
I think a coordinate can be represent by using the pair data structure. Pair<double, double> point.

**Comment by hwkchia** [comment]
Woah.. you predicted our first recitation question!  But other than `Point<Double,Double>`, how can we represent with whatever we have come across in the first lecture?

**Comment by LimZiXiong** [comment]
ImList can also be used to represent a point as it can store more than 1 value.
