### ISSUE TITLE
InputMismatchException when debugging and time limit exceeded on codecrunch

### ISSUE THREAD

**Issue by lequinus** [nus-cs2030/2324-s2#142]
# Summary

Had some issues with my implementation of Lab 3, when submitting on codecrunch and attempting to run on terminal i got received time limit exceeded, probably indicative of a infinite loop somewhere in my code. However while trying to debug on VSCode (first time using) I received a strange InputMismatch error while trying to input in java Main < 1.in into the terminal window. I can confirm that there are no typos in any of my .in files and my Main file as well. Not sure how to go forward from here so any help/advice on how i should go about debugging my infinite loop problem as well would also be appreciated. Thanks!

## Screenshots

<img width="795" alt="Screenshot 2024-02-28 at 1 05 43 AM" src="https://github.com/nus-cs2030/2324-s2/assets/106734444/55c0363e-68af-42a6-bb93-1a6734a0df81">
<img width="1871" alt="Screenshot 2024-02-28 at 1 04 17 AM" src="https://github.com/nus-cs2030/2324-s2/assets/106734444/0903135c-ab14-4c60-a901-95896c32d07c">

**Comment by iceflakes12** [comment]
ur first screenshot could indicate an infinite loop, hence resulting in time limit exceeded on codecrunch

ur second screenshot has nothing to do with your code, your 1.in file might not be in the exact format needed to parse into Main which is why Main throws such an error.

Either way if you dont want to deal with that and you want to be able to debug fast just ask your friends for their 1.in files and likely u wont be facing this issue.

**Comment by iceflakes12** [comment]
Also next time dont cut off the error message into half, u basically cut away the most readable part of the error message so it is also hard to say for sure why u r having this InputMismatchException
