### ISSUE TITLE
Exercise 4 Level 4

### ISSUE THREAD

**Issue by allis-g** [nus-cs2030/2324-s2#148]
Hi, does anyone know how to fix this error? I have used ? super T, S as Integer is a subclass of Number hence I thought both <String, Integer> and <String, Number> during method call would work. But currently has error when calling <String, Number>. I have also tried to change my Obj2StrLen class to implement <Object, Number> then in this case the error would fall on <String, Integer>. Thanks!
<img width="1082" alt="Screenshot 2024-02-29 at 10 18 07 AM" src="https://github.com/nus-cs2030/2324-s2/assets/161267008/cbdc5432-5599-4a51-9a5d-7cb8120e6659">
![Screenshot 2024-02-29 at 10 18 07 AM (2)](https://github.com/nus-cs2030/2324-s2/assets/161267008/8d436a26-99ba-43aa-b554-de91dd564765)

**Comment by xiang-qiuyu** [comment]
I think the main issue with your code is String super Object will work but you cannot Number super Integer so you will fail the test case.

I think you can try <? super T, ? extends S> instead!

Main is passing in <String, Number>  where your T = String and S = Number, but Transformer is <Object, Integer>.  So you will be trying to pass <Object, Integer> into <? super T, ? extends S> which is <? super String, ? extends Number>. Since Object is a super class of String, Object super T works and Integer is a subclass of Number, Integer extends Number works.

Also, this is just how I try to make sense of it but tbh I'm quite confused too haha

**Comment by allis-g** [comment]
Thanks for the clear explanation!
