### ISSUE TITLE
Excercise #3 Level 4

### ISSUE THREAD

**Issue by LuXLemonade** [nus-cs2030/2324-s2#152]
"If your program has been designed correctly, you should not need to modify your existing classes or level3.jsh"

So I completed this level by modifying my existing classes and I would like to know how do I do so without having to do that. The main issues I encountered were referencing magic numbers before the super() constructor was called since I declare attributes like SmallCruise having 1 loader within the class itself.

I passed this test case by declaring all these within the parent Cruise class and having protected static getters for both SmallCruise and BigCruise to access but that means I will need more and more attributes added if there are going to be more types of Cruises in the future.

**Comment by ZHD1987E** [comment]
Inheritence and polymorphism.

Cruise can have its derivatives, the Small Cruise Version and the Big Cruise Version. All should work with being serviced much like the Generic Cruise Version.

**Comment by zuoshihua** [comment]
`SmallCruise` and `BigCruise` should have `private` access to their own attributes. These attributes should not be inside `Cruise`.

To overcome magic numbers, declare them as `private static final`. E.g.

```java
private static final PASSENGERS_PER_MINUTE = 50;
```

`SmallCruise` and `BigCruise` may have their own unique attributes or methods but they always can be treated as a `Cruise` because of the "is-a" relationship.

**Comment by LuXLemonade** [comment]
I understand that SmallCruise and BigCruise inherits Cruise however I cant declare this private static final attribute under them as they say I can't reference all these numbers before calling my super() constrctor.
