### ISSUE TITLE
rounding error in lab 3 case 5 on code crunch

### ISSUE THREAD

**Issue by megankhoo24** [nus-cs2030/2324-s2#157]
Idk why it’s giving me 0.385 in codecrunch instead of 0.386 when rounding from 0.385500 (on my laptop it rounds correctly to 0.386 from 0.385500 tho)

`String.format("[%.3f %d %d]", average, numServed, numLeft)`

i've also already tried `String averageWaitTime = String.format("%.3f", Math.round(average * 1000.0) / 1000.0f)` and even BigDecimal

any help would be greatly appreciated thank you!

<img width="530" alt="Screenshot 2024-03-01 203027" src="https://github.com/nus-cs2030/2324-s2/assets/156740952/03cb5756-c38a-4d3d-a2bb-7d728e605899">

<img width="426" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/156740952/2a55a433-aae8-4c1e-bf2d-7f2e88c4f5d8">

**Comment by gnimnix** [comment]
Unfortunately, this error might be because of how you are computing your total `waitTime`. I see you are computing the total `waitTime` by taking the difference between the total `startWait` time and total `endWait` time. But this might be different from the intended solution of immediately summing up the difference between `timeServed` and `arrivalTime`.

There are [rounding issues](https://www.baeldung.com/java-double-precision-issue#:~:text=To%20sum%20up%2C%20rounding%20error,when%20dealing%20with%20this%20problem.) across all programming languages and the difference in how you compute your values might explain why the rounding is off by a tiny bit. Your laptop might be working fine since it is newer and more precise but that might not be the case for the grading servers.

You can try changing how you compute your total wait time by immediately summing up the wait time when the customer is served.
