### ISSUE TITLE
Excercise #3 Level 5

### ISSUE THREAD

**Issue by LuXLemonade** [nus-cs2030/2324-s2#159]
With this error I suspect that my ordering of the loaders are wrong, are there any suggestions to fix this? How is the maintainance processed? I currently use a dummy service with an additional 60 min end of service time and only pass it from ACTIVE to EXPIRED if the service has my dummy name.

What are the ways to sort the Loaders if I can't use a comparator, and inserting an item into the ImList mid loop might mess up the loop?
![Screenshot_20240302_083150_Chrome](https://github.com/nus-cs2030/2324-s2/assets/86890156/58f59b1a-e331-4e40-9470-cb1ebd6f93a1)

**Comment by gnimnix** [comment]
Assuming your level 3 is correct, this means that there is some logic error in processing `RecycledLoader`. From your post, are you using a dummy service to simulate the delay of 60 minutes? How did you store and process this value of 60 minutes since `Service` only stores `Loader` and `Cruise` objects?

Why do you need to sort your `Loader`?

**Comment by LuXLemonade** [comment]
Yes, I am using a dummy `Service` to simulate the delay.
![image](https://github.com/nus-cs2030/2324-s2/assets/86890156/4698c27f-cfd3-4f52-ac79-4cdfc625ee57)

This `Service` is then sent to `ACTIVE` again. The check for "" is to ensure there are no reprocessing of `RecycledLoader` that came back from maintainance.

I'm asking if sorting is required since from my error above I suspect that my issue is that the `Loader` and `RecycledLoader` are not processed in the right order as I send back the `RecycledLoader` back into `ACTIVE`.

**Comment by gnimnix** [comment]
You do not need to sort your `Loader`, though it is possible but I do not see how it helps since it is not guaranteed that the `Loaders` will serve in order according to their IDs. For instance, `Loader #2` might come become available earlier than `Loader #1` if they serve different `Cruise`.

I think the problem with your current implementation is that it puts `RecycledLoader` to the end of the queue when it should become available earlier. For e.g., over here `Loader #12` should become available earlier than `Loader #13` but because the dummy service re-inserts `Loader #12` at the end of the queue, making it available after `Loader #13`.

You might want to try a different way of simulating `Loader`. Such as creating a new `RecycledLoader` class and in your `Service` class, get the maintenance times from the `Loader` objects and add to `getServiceEndTime()`.
