### ISSUE TITLE
How does `StagedFare` really work?

### ISSUE THREAD

**Issue by ZHD1987E** [nus-cs2030/2324-s2#164]
Getting error because I somehow implemented `StagedFare` incorrectly. Do we:

- Take culmunative distance and determine the fare from this single result? (that was my idea)
- Compute the fare for each leg of the trip and sum them up?

Even so, I am not sure how the fare works. I am thinking that the distance and fare bands are culmunative (e.g. the first 4000 (or less) metres you get charged some money, and the next 7000 (or less) metres you get charged some money). But do they mean something else? (e.g. you get charged some money if it is less than 4000 metres, and another amount if it is 7000 metres (but more than 4000 metres, of course!)).

**Comment by LimZiXiong** [comment]
I computed the fare for each leg and can't pass the testcase as well. Doesn't help the testcase uses TestTrain so we have no idea what each station distance is

**Comment by samuelneo** [comment]
> Compute the fare for each leg of the trip and sum them up?

I did this and it worked

the bands are not cumulative. taking the example of `StagedFare sf = new StagedFare(4000, 90).add(7000, 110)`:
- a leg with a distance of 3000m would cost 90
- a leg with a distance of 4000m would cost 90
- a leg with a distance of 5000m would cost 110
- a leg with a distance of 7000m would cost 110
- a leg with a distance of 8000m would cost 110 (since there is no specification for distances >7000m)

more generally, to find the fare for a leg of distance $k$, find the smallest distance $d$ in the table such that $d \ge k$ and choose the fare associated with $d$. if no such value exists for $d$, choose the largest value in the table as $d$

**Comment by ZHD1987E** [comment]
Thanks, now it works.
