### ISSUE TITLE
PA 1 Compile error

### ISSUE THREAD

**Issue by Yuxin-Mellisa** [nus-cs2030/2324-s2#181]
<img width="463" alt="截屏2024-03-14 下午11 34 12" src="https://github.com/nus-cs2030/2324-s2/assets/157778558/949c938b-3b57-40e6-bc63-b66583153096">
what does this mean? 
it means the nutri class cannot have other method?
or it means that because sth like
Pair<String, Integer> pair = new pair(name, mg) where for mg the compile type is int?

**Comment by mChewWW** [comment]
You definitely can have other methods in nutri class. From google:

"In my experience, this warning can often be caused by using something like an ArrayList without specifying the type which it should expect to hold (i.e. using ArrayList a = new ArrayList() rather than ArrayList<String> a = new ArrayList<String>()). The compiler is, in my example case, warning you that your code isn't going to do any checking for you that the values you add to it are any particular type. In a production application, it would likely be good to specify types, but in a test app, you're free to ignore the warnings if you're not concerned about them."

Instead of this:
Pair pair = new pair(name, mg) 
I think it should be this instead:
Pair<String,Integer> pair = new Pair<String,Integer>(name,mg)

or whatever types you are using in your Pair. check your ImList declarations too.

**Comment by hwkchia** [comment]
I think you missed out type parameterization for pair... `new Pair<String, Integer>(name, mg)`

**Comment by BZAStudent** [comment]
Prof Henry comment should be correct. I also had unsafe warning but i fixed after i type parameterise my Pair

**Comment by Yuxin-Mellisa** [comment]
yes I got it thank you!

**Comment by TongZhengHong** [comment]
you can compile your Java files in the terminal with the additional flag `-Xlint` to see the exact error
``` shell
javac *.java -Xlint
```
