### ISSUE TITLE
Exercise 05 typecasting query

### ISSUE THREAD

**Issue by zzzlou** [nus-cs2030/2324-s2#212]
Hi Prof,

In the lecture slide you provided, there is a snippet:
```
@Override
public boolean equals(Object obj) { 
    if (this == obj) {
        return true;
    }
    if (obj instanceof Maybe<?> other) {
    }
    return false;
}
```
` if (obj instanceof Maybe<?> other)` isn't this line essentially doing typecasting? 

It confuses me because previously you said typecasting is not allowed in this course.

**Comment by yolotouch** [comment]
Based on other threads and exercises, this is not explicit type-casting, but only type casted if it is an instanceof. So this is allowed for us to use

**Comment by weikiatt** [comment]
I think its generally allowed in the equals method because I don't think there are any other ways to check for equality between different objects? If they are objects of the same class, then only you can proceed with checking their properties etc. to determine whether they are equal. If they are not of the same class, and you try to access properties that the object don't have, it'll result in an error

**Comment by mChewWW** [comment]
as already mentioned, explicit typecasting (int a = (int) b, where b is a double), is not allowed. the typecasting via instanceof is considered to be implicit.
