### ISSUE TITLE
Trouble with generics for exercise 5 Maybe

### ISSUE THREAD

**Issue by mChewWW** [nus-cs2030/2324-s2#224]
![image](https://github.com/nus-cs2030/2324-s2/assets/156818769/8a6b2846-5eea-48a6-8560-bfd5be638274)

I've managed to make everything else work for this exercise but my "or" method seems to be giving me trouble with the hidden test cases (worked fine for the ones given in the task itself).

![image](https://github.com/nus-cs2030/2324-s2/assets/156818769/dc0ab32c-5817-4134-96b4-b92c90cb951a)

My method header was originally ```public Maybe<? extends T> or(Supplier<? extends Maybe<? extends T>> supplierMaybe)```
which also worked for the given test cases and had the same error upon submission.

I was surprised that it still did not work when I intentionally made the type Maybe<?> just to see if it would work, so now I'm confused what I did wrong.

**Comment by Jeremythong2002** [comment]
Based on what I understand: 
1. Generally, the generic method specification should not just be a wildcard, there should either be an upper bound or lower bound 
2. Based on the question, the or Method takes in a Supplier of a Maybe<T>, so I took that as a hint that the return type for or should be Maybe<T> 
3. The error that you are seeing is because once you place it inside a Maybe, they are not subclasses already. Maybe<?? and Maybe<A> have no relations. You need to use an upper bounded wildcard to create the relationship.

**Comment by w1nsl** [comment]
My or method returns the type Maybe<T>

**Comment by mikio13** [comment]
The or method should return` Maybe<T>` (same type as the Maybe object calling this method). So instead of directly returning `supplier.Maybe.get()`,  extract the value inside the `supplier.Maybe.get()` (use .get() on it), then wrap it inside a `Maybe<T>` and return it instead.

**Comment by mChewWW** [comment]
> The or method should return` Maybe<T>` (same type as the Maybe object calling this method). So instead of directly returning `supplierMaybe.get()`, extract the value inside the `supplierMaybe.get()` (use .get() on it), then wrap it inside a `Maybe<T>` and return it instead.

would this not require me to make the get() method public?

**Comment by arinng5** [comment]
> > The or method should return` Maybe<T>` (same type as the Maybe object calling this method). So instead of directly returning `supplierMaybe.get()`, extract the value inside the `supplierMaybe.get()` (use .get() on it), then wrap it inside a `Maybe<T>` and return it instead.
> 
> would this not require me to make the get() method public?

yes the get() should be public for it to work right

**Comment by Andrew22Teoh** [comment]
Does anyone know why something like `public Maybe<? extends T> or(Supplier<Maybe<? extends T>> s) {}` does not work? I would expect this to take in any Supplier<Maybe<Class>> where Class is a sub-class of T, in which case the method would make perfect sense.

However, I get this error:
![image](https://github.com/nus-cs2030/2324-s2/assets/122327616/39b74736-76fd-4913-aed9-46a2642be078)
Which doesn't seem to make sense to me, as Supplier<Maybe<Integer>> should appear to be a sub-class of Supplier<Maybe<? extends Object>>.

**Comment by LinusLee17** [comment]
> > > The or method should return` Maybe<T>` (same type as the Maybe object calling this method). So instead of directly returning `supplierMaybe.get()`, extract the value inside the `supplierMaybe.get()` (use .get() on it), then wrap it inside a `Maybe<T>` and return it instead.
> > 
> > 
> > would this not require me to make the get() method public?
> 
> yes the get() should be public for it to work right

supplier.get().get() won't work because get() is private so supplier.get() should first be declared as a Maybe<T> before get() can be called on it

**Comment by CSnoobCS** [comment]
> > > > The or method should return` Maybe<T>` (same type as the Maybe object calling this method). So instead of directly returning `supplierMaybe.get()`, extract the value inside the `supplierMaybe.get()` (use .get() on it), then wrap it inside a `Maybe<T>` and return it instead.
> > > 
> > > 
> > > would this not require me to make the get() method public?
> > 
> > 
> > yes the get() should be public for it to work right
> 
> `supplier.get().get()` won't work because get() is private so `supplier.get()` should first be declared as a `Maybe<T>` before get() can be called on it

Can someone enlighten me what's the way to go around it?

**Comment by Andrew22Teoh** [comment]
Based on what I have figured out so far, hope this helps! @CSnoobCS 

The first thing to note is that your method return type should rarely (if ever) include wildcards, even with upper or lower bounds. For this reason, the return type should be `Maybe<T>` instead of `Maybe<? extends T>` or even `Maybe<? super T>`. This helps with type safety for future operations that may want to use the output of your method.

The second thing is that you do a pseudo-typecasting operation on the outputs of certain bounded wildcard types, which can be helpful. For instance, if you take in an input of type `Supplier<? extends Maybe<? extends T>> supplier`, you know that `supplier.get()` will return you an object of type `? extends Maybe<? extends T>>`. But if you were to assign `supplier.get()` to a type-defined variable, you can remove the wildcard from the type. 

Eg. You want to obtain a `Maybe<? extends T>` instead of a `? extends Maybe<? extends T>` from your `supplier`. You could create a variable by doing `Maybe<? extends T> temporaryMaybe = supplier.get()`. In this way, you are able to handle the wildcard type and obtain a definite type from it without explicit typecasting. 

This same method can be helpful for you to obtain an object of type `T` instead of `? extends T` from your `Maybe<? extends T>` object! From there, you can wrap your obtained `T` value with a `Maybe` and return it safely without type issues.

Hope this helps!
