### ISSUE TITLE
[Lab 04 Level 6] Scanner input not working for Roster in Main

### ISSUE THREAD

**Issue by Gracesong146** [nus-cs2030/2324-s2#246]
# Summary

[Lab 04 Level 6] Scanner input not working for Roster in Main

## Description:

when i use a scanner to get the user input, it always replaces the whole Course's assessments, and the Roster add() method does not work as intended, but it works when i key in the strings manually without asking for user input

## Code Snippets
<img width="430" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/62082817/fa907485-b9cf-4742-b228-4b4e307837ac">

**Comment by zuoshihua** [comment]
In your `add` method, are you using `Optional`'s `orElse` method? Or are you checking the content of the strings (function arguments) to determine how to insert the new record into the roster?

The reason I asked this is because if you are checking the content of the strings, using `Scanner`'s `next` method may produce a different string compared to entering manually.

**Comment by Gracesong146** [comment]
i found my issue!

apparently everything was right but my keyableMap.get() haha

**Comment by ZHD1987E** [comment]
@Gracesong146 great on finding it! Mind if you close this issue to declutter to forum yeah?

**Comment by Gracesong146** [comment]
Thank you!
