### ISSUE TITLE
Clarification on Level 5 requirement

### ISSUE THREAD

**Issue by selina614** [nus-cs2030/2324-s2#27]
Hi, I do not understand what am I supposed to modify for method findMaxDiscCoverage since the original code is able to take in ImList of Point objects.
![image](https://github.com/nus-cs2030/2324-s2/assets/156488480/4c5c69aa-d85c-4892-94a1-20f2f7d502dc)

**Comment by weikiatt** [comment]
I think you're supposed to try to reuse the functions you have created in the earlier levels if possible?

**Comment by ZHD1987E** [comment]
The entire `main.jsh` script is written in a non OOP manner (which reflect what happens when I deal with people who never try to do modularisation): you are supposed to try to make everything in the `main.jsh` file modularised (e.g. creating methods in the circle class and to interface it with your main driver)...
