### ISSUE TITLE
wrong rest time obtained?

### ISSUE THREAD

**Issue by andrelau123** [nus-cs2030/2324-s2#274]
cs2030 project
<img width="660" alt="Screenshot 2024-03-21 at 2 06 20 AM" src="https://github.com/nus-cs2030/2324-s2/assets/81068338/da744a2c-43e5-4be4-802f-23a8a6f5e2b5">
# Summary
unable to pass this test case as my rest time is somehow wrong? i update the resttime to the server's next avalible time in the serve event.

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary

**Comment by Jeremythong2002** [comment]
The questions mentions "That is to say, whenever a server rests, it will then know how much time it has to rest." 

I take this as a hint that the rest time should only be determined after they have finished serving a customer rather than in the serve event as you mentioned.

**Comment by ZHD1987E** [comment]
You ONLY get the rest time at the time the server is finished serving someone as what @Jeremythong2002 mentioned.

**Comment by andrelau123** [comment]
hmm but is there are difference obtaining the rest time in serve event rather than the done event? all serve event will lead to done events when it is finished

**Comment by iceflakes12** [comment]
> hmm but is there are difference obtaining the rest time in serve event rather than the done event? all serve event will lead to done events when it is finished

Serve and Done events have different event times. Since you are likely going to be passing the same supplier restTimes into every human server, this means that every time you call on restTimes.get(), this actually changes the state of supplier for every single server. This means that the time you call your restTimes.get() is actually important as well, and the specs require you to call this only in the Done event. 

Let me quote an example since what I said above might be hard to understand.
Server 1 starts serving customer 1 at 0.500
Server 2 starts serving customer 2 at 0.600
Server 2 done serving customer 2 at 1.000
Server 1 done serving customer 1 at 1.200

From this example, you see that if you call rest time in the serve event, server 1 receives rest time before server 2, while if you call rest time in done event, server 2 receives rest time before server 1. In this case, because of my explanation above, it is actually important that server 2 receives rest time before server 1.

**Comment by andrelau123** [comment]
thx for the help:)
