### ISSUE TITLE
cannot use set for lab4?

### ISSUE THREAD

**Issue by clarequek** [nus-cs2030/2324-s2#279]
# Summary
I used the entrySet function from ImmutableMap for my KeyableMap's toString. It works fine on my terminal but it seems to keep giving me this message on codecrunch. Any advice?

<img width="635" alt="Screenshot 2024-03-21 at 2 49 56 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164228670/5e708f28-6fec-4fe4-8dfe-9b0281b19195">

## Code Snippets

Here's my code for your reference:
<img width="559" alt="Screenshot 2024-03-21 at 2 51 03 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164228670/95b2954c-597f-4744-9d45-18923ab03194">

**Comment by delulu04** [comment]
I think you can consider iterating through the whole map and initialising a boolean variable to true to check if the current entry is the first in the map. 

        boolean isFirst = true; 
Then u cld do something like this in the for loop 
            if (isFirst == false) { 
                output += ", "; 
            } else { 
                isFirst = false; 
            }

**Comment by LimZiXiong** [comment]
You cannot use entry set. You can take at look at the top of the labsheet it demonstrate how to iterate through the map without using entryset.

**Comment by jennipho** [comment]
I also faced this issue - what helped me was that I didn't run through the set and instead just the map in my for loop, aka I did .... : map instead of .... : map.entrySet()

**Comment by tarshalim** [comment]
adding onto the comments above, you cannot use entrySet, but i realise that you made use of entrySet().size() in order to prevent the inputation of comma and space for the last entry. 
To overcome this problem, you can try using a boolean instead. 
so 1) you dont add comma if there's only 1 entry and its the first entry in the map
2) the adding of comma is done before you append entry to output, so the last entry will not have comma behind it


boolean firstEntry = true;
for (Map<String, V> entry: map) {
  
//adding commas
 if (!firstEntry) {
	output += ", ";
 } else {
        firstEntry = false;
 }
 
 output += entry.getValue();
 
}

**Comment by hzhitong** [comment]
hi! i faced the same problem as you

what i did was for the parameters of the for loop, instead of writing 
for(Map.entry<String, V> entry: map.entrySet())    or 
for (String key : map.keySet()) {

i did 
for (Map.Entry<String, V> currentMap : map)  
where iterates through each entry (key-value pair) in the map instead

**Comment by hanlinnnnn** [comment]
iterating directly through the map as shown in the assignment rather than entrySet() works perfectly fine for me!

**Comment by zzhengweii** [comment]
the issue is in your this.map.entrySet() as this method belongs to the ImmutableMap class which uses java.util.set, instead you can easily loop through this.map by using the code prompt given in Code Crunch.

**Comment by jwoongg** [comment]
I think entrySet() is the banned API, your perhaps should take some value from another class

**Comment by juliannxe** [comment]
Yeah you can't, the preamble of the CodeCrunch exercise shows you how to iterate if need be. Something to do with Entry & Map in the ImmutableMap class
