### ISSUE TITLE
Exercise 5 Level 4 "or" method

### ISSUE THREAD

**Issue by harvestingmoon** [nus-cs2030/2324-s2#287]
# Summary

Description of the question / problem here.

Was trying to find a way to get an "or" method however I realized that the optional class that I am producing would need to be called.

## Description:

Currently, the only solution I can think of to bypass this method would be to not private the "get" method type when solving for "or".  Either that or explicit typecasting. Is there anyway to convert it without having to use the inner "get"?

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)
![fucking useless](https://github.com/nus-cs2030/2324-s2/assets/81916103/035020be-42dc-41dd-95b9-3fcf584b4fbd)

**Comment by feliciahmq** [comment]
perhaps you can try safe typecasting? create a convert method to change the type...

**Comment by samuelneo** [comment]
I'm not sure what your approach is, but you don't need explicit typecasting (or a convert method). you might want to refer to the implementation of `Maybe::flatMap` gone through in class, the approach for `Maybe::or` should be quite similar

**Comment by afaann** [comment]
had the same issue and consulted my TA. He suggested something like
 Maybe<? extends T> m = supplier.get();
        T t = m.get();
        return Maybe.<T>of(t);

for the case of this.isEmpty().
i.e sort of typecasting but not actually typecasting.
Probably also having something to do with why prof said in lecture to split up your code instead of putting all the steps together.

**Comment by JovanFoo** [comment]
my code is similar to what afaann suggested and it works so maybe you can consider doing that too!

**Comment by yishao17** [comment]
my code is similar to afaann too, but at the top, mine is Supplier<? extends Maybe<? extends T>>. 
then continued with afaann's code chunk! 

I hope this helps :")

**Comment by nicklass8** [comment]
Hi i also had this error and it only works if the return type of your or method is a Maybe<T> instead of Maybe<? extends T>. Hope this helps!

**Comment by weiyangng** [comment]
try changing the input to Supplier<? extends Maybe<? extends T>> before changing the type in the if (this.isEmpty())

**Comment by OthnielChang** [comment]
hello, just wanted to ask if the main idea is to not return wildcard types (for type safety), then why is it ok to declare the first maybeSupp.get() as a Maybe<? extends T>>?

**Comment by samuelneo** [comment]
the idea is that you have a Supplier of a `? extends Maybe<? extends T>` and need to return a `Maybe<T>`. you can't assign a `? extends Maybe<? extends T>` to a `Maybe<T>` directly, since generics are type invariant. you'll have to first assign it to a `Maybe<? extends T>`, then get out the value of type `T` so you can wrap it in a `Maybe<T>`

**Comment by ZHD1987E** [comment]
I hope that you figured it out. If you did, as a courtesy, mind if you close this issue?

Thanks @harvestingmoon

**Comment by harvestingmoon** [comment]
Closed as resolved, thanks everyone for your kind inputs!
