### ISSUE TITLE
main.jsh 

### ISSUE THREAD

**Issue by BZAStudent** [nus-cs2030/2324-s2#29]
## Description:
Hello. Am I suppose to private my values for Point.java and Circle.java? If i private them, main.jsh will not work because some methods uses p.x and p.y. 

I by passed this problem by deleting the other methods except for createUnitCircle and findMaxDiscCoverage. Am I suppose to do that?

## Code Snippets

Attach code snippets (if any)

## Screenshots

![image](https://github.com/nus-cs2030/2324-s2/assets/156635387/963781ef-c085-4626-a294-2eca286a8a33)

**Comment by weikiatt** [comment]
You can try using the functions from your classes instead of the ones given to you in main.jsh

**Comment by LimZiXiong** [comment]
I deleted/modified all method that ask for things and passed the test cases

**Comment by codingtemp** [comment]
As stated in the task - ***By applying the object-oriented principles of abstraction and encapsulation, re-design the program as a object-oriented solution to the problem.***

To fulfil encapsulation, low level data should be hidden (using private), and methods should be packaged in the right class. For instance, when creating a method to move a point, it is more logical to place that method within the point class rather than requesting two points in the main class.
