### ISSUE TITLE
Lab5 Level 4 equals method 

### ISSUE THREAD

**Issue by allis-g** [nus-cs2030/2324-s2#305]
## Description:

Hi, for level 4 it says that : Two loggers are equal, if and only if, both the wrapped value as well as the logs are the same.
However, when I try to implement the code below the following input will not output true but false instead. Could anyone help to explain the logic error that I'm encountering? Thanks!

input: Log.<Integer>of(5).flatMap(x -> Log.<Integer>of(x)).equals(Log.<Integer>of(5)) // monad right identity

My code:
 Log<?> other = (Log<?>) obj;
        return this.value.equals(other.value) && this.log.equals(other.log);

*edit: seems like the wildcard that i wrote doesn't show so for the code i wrote Log bracket question mark bracket other = Log bracket question mark bracket obj

**Comment by yolotouch** [comment]
When empty strings are logged in the flatMap, even if the string is empty, the strings may have line breaks (depending on ur implementation). So you might want to check that out and handle it accordingly.

**Comment by LimZiXiong** [comment]
Had this problem too your string and how it was formatted matters

**Comment by kingcard02** [comment]
If you check the log Log.<Integer>of(5).flatMap(x -> Log.<Integer>of(x)) you will notice that it is \n which is not the same as Log.<Integer>of(5) whose log is an empty string. If the log for either the original Log or the Log in flatMap is an empty string you may want to just return the other log which is not empty instead of adding \n.
if (string1 == "") {
            return string2;
        }
        if (string2 == "") {
            return string1;
        }
        return string1 + "\n" + string2;

**Comment by yolotouch** [comment]
yup mine was similar to @kingcard02 's implementation

**Comment by kshoo-0957315** [comment]
Does the first line not violate the typecasting restriction? I have no idea how to approach this problem differently other than declaring the object other as a log object

**Comment by ethan267ong** [comment]
can anyone explain the logic behind this, am currently getting false instead of true for the last 3 cases

**Comment by Yiting55** [comment]
actually the question states that the input is a Log object, so no need typecasting in the implementation. As the question says, as long as 'both the wrapped value and the logs are the same', the two Log objects are considered equal. So only need to check this.value().equals(obj.value()) and this.log.equals(obj.log())

**Comment by PengRongNeo** [comment]
I failed the last few test cases returning false instead of true, and thanks to the comments above, I realise that my implementation of flatMap assumes that the Log (returned by the Function after mapper.apply()) has a string log that is not empty (i call it 's') and this.log also is not empty, hence i end up making accumulatedLog = this.log + /n + s then calling the of method and putting the accumulatedLog in. This is wrong as my accumulated Log will always have a /n regardless of whether s is empty. Hence, there should be an if condition in front such that if s was empty, return Log.<Integer>.of(v,this.log) //this one does not have the /n anymore

**Comment by ethan267ong** [comment]
thanks for the comments guys really helped me in overcoming this issue, and helped my understanding as well
