### ISSUE TITLE
Difference between Optional<?> and Optional 

### ISSUE THREAD

**Issue by HaoZeHuin** [nus-cs2030/2324-s2#321]
Is there any difference between :
if (x instanceof Optional<?>) 
and 
if (x instanceof Optional)

**Comment by naomiiiwu** [comment]
I think generally the first one is more common than the second one.
if (x instanceof Optional<?>) considers unbounded wildcard
if (x instanceof Optional) does not consider the type parameter at all
personally feels like the first one will be more precise, but both will be correct in terms of checking the instances.

**Comment by Jett-Tan** [comment]
Optional<?> wildcard while Optional is just the raw type

**Comment by sje5398p** [comment]
Optional<?> is more general, allowing x to be of any type whereas just using Optional checks whether x is an instance of the raw type Optional without specifying any type parameter.

**Comment by mChewWW** [comment]
Optional<?> refers to the wildcard while Optional is just a raw type,.

**Comment by dillonph34** [comment]
Java issues a warning when using Optional (the raw type) by itself for type safety, as no information is given on what type Optional should take in. At least in Optional<?>, there is a specification that Optional takes in any type.

**Comment by jwoongg** [comment]
"?" means that it can hold any type of object, "optional" by itself is a raw type

**Comment by yminnnx** [comment]
for if (x instanceof Optional<?>) the check is more generic and allows for any type of 'optional' since the type parameter is unknown 

for if (x instanceof Optional) it does not differentiate between diff Optional instances and hence is discouraged in most cases

**Comment by wdgyn** [comment]
Optional<?> means that the Optional can be of any data type, such as Optional<String>, Optional<Double>, Optional<Integer>, etc.

On the other hand, Optional is just the base type of Optional.

**Comment by lohkeyyy** [comment]
Optional: This is a raw type of the Optional class. It means that you are not using generics, and as such, the type of the value inside the Optional is not specified. Using raw types in Java is generally discouraged since it forgoes the type-checking feature of generics, which helps catch errors at compile time.
Optional<?>: This is a wildcard-parameterized type. The ? is known as a wildcard and it represents an unknown type. This is a way of saying that the Optional can hold any type, but unlike the raw type, it still makes use of generics and the type safety that comes with it. In practice, Optional<?> is a way of declaring an Optional without specifying the type of the value it may contain, while still benefiting from the generics system.
