### ISSUE TITLE
Question about generic methods, specifically in Optional class

### ISSUE THREAD

**Issue by mxtt1** [nus-cs2030/2324-s2#332]
How come for some generic methods such as .of() in the optional object type must be declared in the method call, while other generic methods such as map() do not need the type to be declared when performing a method call?

**Comment by ppv-1** [comment]
my man you are cooked

**Comment by mChewWW** [comment]
i think you are referring to static methods. static methods allow you to create a new object without having to use the 'new' keyword.

for example Optional<String> = new Optional<String>();
as compared to Optional<String> = Optional.<String>of("string");

you dont need to declare the optional type for other methods such as .map because it takes in the same optional type based on what is calling the .map method. 

for example. if a Optional<String> calls the .map method, the .map method will take the optional to be of the String type as well

**Comment by RyanLucasHo** [comment]
The .of() method is a static factory method that creates an optional of a particular type.
e.g Optional.<Integer>of(1) creates an optional of an integer type.

When doing a map, the type of the value wrapped around optional is used. Hence, the type does not need to be declared.

**Comment by juelin708** [comment]
.of()method is the static method for the generic class, and we don't need to attach it to an instance of the class. The method is also generic so we need to declare the typ. However, .map method is not static and need be attached to an instance of the class, for which the type is already declared.

**Comment by LingWL02** [comment]
In Java, type inference enables the compiler to deduce the type arguments for generic methods in certain contexts. Methods like .of() often require explicit type declaration because the compiler needs more information to infer the correct generic type. Conversely, methods like .map() infer the type from the context in which they're used, typically by examining the type of the input parameter or the return type of the method. This inference simplifies method calls, as the compiler can determine the appropriate generic type based on the surrounding code.
