### ISSUE TITLE
can use visual studio code to edit files? (window user)

### ISSUE THREAD

**Issue by megankhoo24** [nus-cs2030/2324-s2#34]
my friend told me that windows does not have a built in editor so she recommended that I download visual studio code (it's free!) and edit the files using that instead of the jshell edit pad. I find it much easier to use :)

**Comment by ZHD1987E** [comment]
For assignments, they don’t really enforce…

But on Unix, there is likely no option for you to open in Visual Studio Code, you may have to rely on whatever text editor Unix gives, including Vim.

**Comment by EnzioKam** [comment]
While we cannot stop you from using other editors when doing your own work, you will only be able to use whatever is provided in the SoC servers during your Practical Exam, which will basically only be terminal based emulators i.e. vim.

So, we will recommend you get comfortable with vim since that will be your only option (unless you use nano or micro) for your exam.

**Comment by gnimnix** [comment]
another tip: you can install the vim extension to use VSCode while learning the vim commands. But do switch to using vim on terminal as you get more familiar with vim
