### ISSUE TITLE
Lab 5 level 5

### ISSUE THREAD

**Issue by caleblowy** [nus-cs2030/2324-s2#340]
## Description:

Hi for lab 5 level 5 f method, im having trouble coming up with a recursive solution. 
I understand that Log(11, "").flatMap(x -> Log.<Integer>of(3 * x + 1, "3(" + x + ") + 1")) will give me Log(34, "3(11)+1") and 
Log(34, "3(11)+1").flatMap(x -> Log.<Integer>of(x / 2, x + " / 2")) will give me Log(17, "3(11)+1 34/2") etc but i cant think of how to implement this

any help is appreciated

## Code Snippets

Attach code snippets (if any)

## Screenshots

Screenshots (if any)

**Comment by wallaacee26** [comment]
hello! you can try implementing the recursive call in the flatMap itself.

for example, using this: "Log(34, "3(11)+1").flatMap(x -> Log.of(x / 2, x + " / 2"))",
instead of flatMap(x -> Log.of(x / 2, x + " / 2")), you could call the recursive function in place of Log.of(x / 2, x + " / 2"), since the recursive function will return a Log<Integer> type anyways. depending on your flatMap implementation, the base case should be appended to the back. hope it helps!

**Comment by RyanLucasHo** [comment]
For recursion, it helps to think about the base case and what it would return and work your way backwards to achieve the desired results. In this case, the base condition would always return a Log object with a value of 1 and "1" as its String. Think of how this return could be used by the previous recursive call and returned upwards to achieve the expected results.

**Comment by Yiting55** [comment]
try to put your function f(x) when you call flatMap() to concatenate the string, such that you can get the recursion

**Comment by caleblowy** [comment]
resolved! thanks everyone for the help greatly appreciate it
