### ISSUE TITLE
Lab5 Level 5 reversing function output

### ISSUE THREAD

**Issue by kohsweehong** [nus-cs2030/2324-s2#346]
How should I reverse this output until it reaches the base case? It works for sum() but not for f().

## Screenshots

<img width="105" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/156646904/419bcec1-5220-4aba-9e60-52547b62213d">

**Comment by niclow236** [comment]
For the sum() function, the output starts at the base case whereas for f() it ends at the base case. Since the question didn't explicitly state that u cannot create helper functions, perhaps you could try creating an alternate flatMap() method which adds the new logs in a different order and use that method inside f() instead of the regular flatMap()

**Comment by ccyenn** [comment]
you can consider reversing the order of your flatMap() methods

**Comment by kohsweehong** [comment]
Okay, have got the logic of it! Thanks guys!

**Comment by kohsweehong** [comment]
Okay, have got the logic of it! Thanks guys!
