### ISSUE TITLE
Lab 5 Level 5 - how to approach

### ISSUE THREAD

**Issue by xin-yi-phang** [nus-cs2030/2324-s2#363]
Hi! I'm currently attempting level 5 of lab 5. I'm unsure how to approach the question

For the recursive functions, would it be advisable to call a separate helper function to do the recursion, that way I can keep track of the logs for every iteration?

for example, I have the `Log<Interger> f(int n)` function which returns a function call to a separate method `k(n, null)`. in the `k` method, I can conduct further checks to determine if the log (String) input is null or has an item.

I'm afraid that I have overcomplicated my code. Am I in the right direction?

**Comment by isaacyclai** [comment]
Actually it's probably simpler than you think. You can accomplish whatever you want using only a Log and flatmap. It's mainly a matter of figuring out (1) which Log to call flatmap on and (2) what function to pass in as the input of flatmap. Any variation with the printed output can be controlled by creating a Log with the appropriate string.

**Comment by proteaninja** [comment]
The `Log<Interger> f(int n)` function is on the right track. Like what was mentioned above, you're able to solve it using Log and Flatmap within this function in order to sort out your code. I personally don't think a separate helper function is necessary to keep track of the logs for every iteration. Try focusing on Log and Flatmap and it should be relatively straight forward once you know how to use them.

**Comment by UserNameWasTakenAlreadyy** [comment]
hihi try not to overthink the solution. Utilise the methods you have alrd defined in Log as Levels 2 to 4 are building you up to be able to solve Level 5. Perhaps if you want to add a Log to another Log using an anonymous function, you could look at flatmap? Do take note of the order you use flatmap in tho. Iirc the 2nd part of Level 5 wants you to reverse it.

**Comment by xin-yi-phang** [comment]
Hi!! Finally solved it 😭  thank u everyone for ur help!! :)
