### ISSUE TITLE
"null value detected"

### ISSUE THREAD

**Issue by blacksesamezongzi** [nus-cs2030/2324-s2#370]
## Description:

I try to use if (value == null) , but it says it is invalid, how could i justify?

## Code Snippets

 23     static <T> Log<T> of(T value, String print) {
 24         if (value instanceof Log || value == null || print == null) {
 25             return Optional.ofNullable(null)
 26                 .orElseThrow(() -> new IllegalArgumentException("Invalid arguments"));
 27         }

**Comment by huangtian666** [comment]
hii, you can use `Optional.ofNullable(value)` to check if value is a null and `Optional.ofNullable(print)` to check if the string is also a null.

**Comment by HQ2100** [comment]
you can try to play around with Optional,ofNullable(value).map(.....) and .filter() to check for nulls and filter not instanceof log

**Comment by ArkAzrael** [comment]
As per module policy you must NEVER use null anywhere in the code.
Just use Optional.ofNullable(value).orElse()
the or else will unwrap it for you

**Comment by nicklass8** [comment]
CS2030 does not allow you to check if the value is null through this method, hence the whole point of teaching us Optionals to handle any potential null values that we may encounter

**Comment by RadieonAjax** [comment]
You can just continue off from the hint which was included in Level 1:

```Java
static <T> Log<T> of(T value, String log) {
    return Optional.ofNullable...;
}
```

With the inclusion of `filter` to check for Log instances, you can make use of `ofNullable` to return the IllegalArgumentException if the value/string is null.

**Comment by s4dha** [comment]
hi, i faced the same error at the start, you have to make use of the Optional.ofNullable(t) from the start and keep on chaining the methods such as filter, and map, or even flatmap. The flatmap that you later define will be useful in this of factory method so that you will not encounter the problems of nested Optionals. It is also recommended to write your .map or .filter in a new line so that its more easier to understand your chained methods and you won't get confused. 

If you face this error below, its likely because of Optional within an Optional, and this is when flatmap comes in handy. I am not too sure about this so someone can correct me if I am wrong! 

Log.java:35: error: incompatible types: no instance(s) of type variable(s) X exist so that Optional<Log<T#2>> conforms to Log<T#2>
            .orElseThrow(() -> new IllegalArgumentException("Invalid arguments"));
                        ^
  where X,T#1,T#2 are type-variables:
    X extends Throwable declared in method <X>orElseThrow(Supplier<? extends X>)
    T#1 extends Object declared in class Optional
    T#2 extends Object declared in method <T#2>of(T#2,String)
1 error

in the end, you have to end it with a terminating function such as orElseThrow(" " ) which throws either the wrapped value inside the Optional container, otherwise it throws the supplied exception. I hope this helps.
