### ISSUE TITLE
When a customer arrives, how does he determine which server or self-checkout to queue at?

### ISSUE THREAD

**Issue by mikio13** [nus-cs2030/2324-s2#386]
# Summary
When a new customer arrives, how does he determine which server or self-checkout to queue at?

## Description 
When both human servers and self checkouts have customers in the queue, which queue should the new customer join?

Right now customers join the first queue that is not full (not necessarily the shortest), so do we just treat the self-checkout's queue as the last one? (People only queue at self-checkout if all human server's queues are full?)

**Comment by dnardnar** [comment]
When both human servers and self checkouts have customers in the queue, which queue should the new customer join?
customers join the first queue that is not full, only if all servers and selfcheckouts are serving/resting.
People only queue at self-checkout if all human server's queues are full? this should be true and also if all human servers are serving/resting and one or more selfcheckout is not serving. there are many possibilities due to the resting of human servers

**Comment by MaverickWongKeJun** [comment]
Your interpretation of it seems to be correct. For each customer that enters, they check the servers sequentially (by order of server number), with the self checkout server queue always appended at the end of the server list. Human servers are considered full if their queues contain queue max number of customer (take note that if the human server, you should only dequeue the customer once the human server is available again). The implementation of the self checkout counter queue is up to your discretion, personally what I did was append a special server at the end of the server list (subclass of server) which contains a queue and a list of servers (another subclass of server). I think you can model your implementation such that your server list contains a list of both human servers and self checkout counters (such that if u have 2 human servers and 2 self checkout counters you will have 4 elements in your server list) but i didnt do that cause i thought the queue handling would become more complicated

**Comment by yushanedi** [comment]
As the others have mentioned, there are multiple ways of approaching the implementation of your queues.  If you're asking about the preference of the servers to queue, I would say it would be based on ascending ID of your current customers list. Eg: It will be served by Server ID 1, Server ID 2, then SCC 3.. SCC 4 etc. The current implementation I had involves keep track of the ID where the SCC servers start and then modify the servers waiting list based on this ID. By doing so, I can update accordingly and be able to differentiate when to create a new Server() or a new SCC().  That being said, there are multiple ways of approaching this problem, so you should choose an implementation that best fits your current code.

**Comment by MoeySeanJean** [comment]
Since the question mentioned that self checkout is numbered k+1 provided there is k human servers, the customer will always check from server 1 to server n (n is the number of human servers and self checkout combined). In short, the customer check for human server queue before self checkout queue. You can implement this by doing extension of your current server class without changing much in other classes.

**Comment by jiancheng37** [comment]
Customers join the first queue that is not full, so the customer will check the servers first from 1 to k to see which server can let them queue. If all servers cmi, then he will check the self checkout queue

**Comment by Jeremythong2002** [comment]
It might be useful to think of it that when you loop through all the self-check out counters, they will all return the same value for their queues. 

Which means that (i) when it hits the first self-check out and there is space in the queue, it will automatically be assigned to the self-check out counter; (ii) when you update the queue of a self-check out, need to make sure to update it such that all the other self-check out will reflect that same queue

**Comment by mikio13** [comment]
Thank you everyone, managed to solve it
