### ISSUE TITLE
L1 Q10: difference between the specifications of the Math and ArrayList

### ISSUE THREAD

**Issue by zenlxy** [nus-cs2030/2324-s2#39]
# Question Description: 

What is the difference between the specifications of the Math and ArrayList, apart from the different methods? How should the methods from these two classes be called?

## Your Contribution:

Math and ArrayList are two different classes. For the Math class, we do not have to instantiate a Math object before calling its methods. The methods in the Math class are static, and we call them directly on the class, such as Math.sqrt(9.0). On the other hand, for the ArrayList class, we have to instantiate an ArrayList object before calling its methods. We use “new” to create an instance, for example, ArrayList<String> list = new ArrayList<>(). Once the object is created, we can call methods on the ArrayList instance, such as adding elements with list.add("one").

**Comment by EnzioKam** [comment]
> we do not have to instantiate a Math object before calling its methods

Exactly. Now to be more specific, we do not need to instantiate an instance of a class to call its **static** methods. For non-static methods, we can only invoke the methods from an instance of the class.

Notice why I phrased it differently from your explanation above. Because we can have a class with both static and non-static methods!

**Comment by hwkchia** [comment]
Included in Lecture01.
