### ISSUE TITLE
test case 3 servers arent resting

### ISSUE THREAD

**Issue by m5x4** [nus-cs2030/2324-s2#390]
## Description 
Not sure why my servers arent resting in this test case, even though i passed the other public cases.
I created a rest class and also updated the next available time of servers in the done class. Thanks in advance!

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/163496829/5f5005b4-d344-4bf6-9f51-a12d0d75c2c1)

**Comment by kubrian** [comment]
Since your timings appear to be earlier than the expected output, maybe you could check if you are referring to the **most updated** version of the server? For example, you made customer 3 queue at server 1 in the form of a wait event, but maybe after server 1 is done serving customer 1, and gets updated with some rest time, the wait event was not able to access this updated time due to referencing the server instance instead of by ID.

**Comment by SumitShinde0702** [comment]
Hey, so here the code is not recognizing that the server is resting. I had an issue similar to this. Here is what I did,
I have a updateServerList  method in RestEvent and that is where I updated the endtime of the server, instead of doneEvent. 
Maybe you can try it. 
![image](https://github.com/nus-cs2030/2324-s2/assets/94443578/0c6b7fee-553c-4b79-85cf-ddad4e49857e)

**Comment by khaixuen** [comment]
perhaps your server passed around is not the one with the most updated finish timing, so i think you can try looping through your server list to find the server with the same server ID (assuming you update the server's finish time in the server list) before writing the logic to access the most updated server finish time

**Comment by Jeremythong2002** [comment]
The issue could also be due to the priority of the rest class. If your servers' rest timing are only updated in the Rest class, it might be the case that the Rest event is not being called by the PQ early enough to register that before the next action is carried out.

**Comment by m5x4** [comment]
thank you all! the time i was getting in my serve class was not the updated one, because my wait event was not entirely correct haha. Thanks!
