### ISSUE TITLE
test case 3 failed

### ISSUE THREAD

**Issue by itzsihui** [nus-cs2030/2324-s2#391]
# Summary
Put a summary of the question
yooo, I don’t know why i failed test case 3. i return rest event after done event if server needs to rest, and return this if server does not need to rest, but i sitll dont get the correct output

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
<img width="758" alt="Screenshot 2024-03-30 at 8 52 40 PM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/964221e5-13f4-4c7e-acb9-a6c0dfe5d389">

<img width="737" alt="Screenshot 2024-03-30 at 8 54 02 PM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/f1c90e15-08de-4c03-ae77-7d8cadd3f4c4">

**Comment by iceflakes12** [comment]
If you want to update server you should have done something like 
this.server = this.server.updateServer(....) but this would have failed anyway since this.server is likely a final attribute.

Why not do something like 
Server temp = server.updateServer(...)

then pass temp into your rest event?

**Comment by iceflakes12** [comment]
Also should you not have passed this.getTimestamp() + restTime into your rest event also?

**Comment by LimZiXiong** [comment]
When you do server.updateServer, due to cs2030 enforcing immutability and since you got through the checkstyle, it means that your updateserver returns a new server. You need to assign your server to this new server like this server = server.updateServer(...).
Also you rest event should capture the server resting finish so you should pass in the server timestamp + resttime

**Comment by SumitShinde0702** [comment]
The code is not recognizing that the server is undergoing a rest period, that's why the new customer is being served by 1 instead of 2. 
A possible improvement could be something like, 
1) checking the polling mechanism you have in simulator 
2) ensuring that in your restEvent, the updateList is properly defined, eg, setting the new timings

**Comment by itzsihui** [comment]
thank you all !!!
