### ISSUE TITLE
How to manage the queue system for self checkout counters?

### ISSUE THREAD

**Issue by 763312** [nus-cs2030/2324-s2#400]
# Summary
Currently, I have a boolean method (HasGlobalQueue)  that differentiates between the self-checkout counters and human servers. The problem with this is that in each event (arrive, serve, wait) I'd have to check whether the server is a self-checkout counter before updating the server list because of the self-checkout queue system. Is there a better way to do this?

![image](https://github.com/nus-cs2030/2324-s2/assets/132988589/410ac304-839a-4f08-85ff-ab32ae3a5c80)

**Comment by MoeySeanJean** [comment]
For my implementation, I just create a SelfCheckout object that has a queue at number k, while the other SelfCheckout objects have no queue. This way, the previous implementation of checking queue can be kept without changing any main logic.

As to differentiate between both types of servers, you can add a method in Server and override this method in both child classes. So when you call the method, the overridden method from child class will be called instead of the one in Server class. This way, your main logic does not need to check which type of server it is, it can just call this method in Server class and the the different overridden methods will do their job.

**Comment by hadyamanisanto** [comment]
> For my implementation, I just create a SelfCheckout object that has a queue at number k, while the other SelfCheckout objects have no queue. This way, the previous implementation of checking queue can be kept without changing any main logic.
> 
> As to differentiate between both types of servers, you can add a method in Server and override this method in both child classes. So when you call the method, the overridden method from child class will be called instead of the one in Server class. This way, your main logic does not need to check which type of server it is, it can just call this method in Server class and the the different overridden methods will do their job.

Do you mean we have to create 2 different Self Checkout classes?

**Comment by MoeySeanJean** [comment]
> > For my implementation, I just create a SelfCheckout object that has a queue at number k, while the other SelfCheckout objects have no queue. This way, the previous implementation of checking queue can be kept without changing any main logic.
> > As to differentiate between both types of servers, you can add a method in Server and override this method in both child classes. So when you call the method, the overridden method from child class will be called instead of the one in Server class. This way, your main logic does not need to check which type of server it is, it can just call this method in Server class and the the different overridden methods will do their job.
> 
> Do you mean we have to create 2 different Self Checkout classes?

Same class, only when you create the object in Simulator class, create 1 with queue and the others without. All should be same class.

**Comment by hadyamanisanto** [comment]
In your implmentation, is the Queue/ImList an attribute in Server class?

**Comment by MoeySeanJean** [comment]
> In your implmentation, is the Queue/ImList an attribute in Server class?

Yep. It should be an attribute in Server class since each server will have its queue.

**Comment by jiancheng37** [comment]
you can think of making humanservers and selfcheckout a subclass of Server, then u can create a imlist of Servers containing both types of servers, so you dont need to check whether the server is HS or SC

**Comment by hadyamanisanto** [comment]
> you can think of making humanservers and selfcheckout a subclass of Server, then u can create a imlist of Servers containing both types of servers, so you dont need to check whether the server is HS or SC

Can human servers be defined as Server?

**Comment by darylchen46** [comment]
I differentiated between my Human Servers and SelfCheckouts by comparing the serverId to the number of human servers/number of selfcheckouts. I did so by passing in the number of human servers/number of selfcheckouts into my event constructors to be used by the methods. Hope this helps

**Comment by TongZhengHong** [comment]
Can consider this approach: 
- Create `HumanServer` class which extends `Server` and has a `queue`
- A self-checkout counter is technically just a `Server` (since it just has ID and next available time)
- Have a `Shop` class that stores an `ImList<HumanServer>`, `ImList<Server>` for self-checkout counters and a `queue` for self-checkout counters

By doing so, you just need to instantiate a single `shop` object and pass it around the various `execute` methods (or whatever you call it) of each `Event` class. The ' Shop ' class will handle all changes to the variables related to human servers and self-checkout counters internally.

**Comment by sje5398p** [comment]
> Can consider this approach:
> 
> * Create `HumanServer` class which extends `Server` and has a `queue`
> * A self-checkout counter is technically just a `Server` (since it just has ID and next available time)
> * Have a `Shop` class that stores an `ImList<HumanServer>`, `ImList<Server>` for self-checkout counters and a `queue` for self-checkout counters
> 
> ```java
> public class Shop {
>     private final ImList<HumanServer> humanServerList;
>     private final ImList<Server> selfCheckoutCounters;
>     private final Queue selfCheckoutQueue;
>     ...
> }
> ```
> 
> By doing so, you just need to instantiate a single `shop` object and pass it around the various `execute` methods (or whatever you call it) of each `Event` class. The `Shop` class will handle all changes to the variables related to human servers and self-checkout counters internally.

How did you manage to do this without facing any cyclic dependency issues? I implemented the Shop class similar to what you mentioned and in my methods I returned Pair<Event, Shop>, and my nextEvent in Event also took in Shop as an argument. ik that's wrong but idk what else to do...
