### ISSUE TITLE
Project Test Case 11/18

### ISSUE THREAD

**Issue by timothyngcy** [nus-cs2030/2324-s2#401]
## Description 
Hey! Did anyone else get this error and who knows what might be the issue with my code?

Thanks for the help in advance!

## Screenshots (if any): 
<img width="588" alt="Screenshot 2024-04-01 at 1 02 41 AM" src="https://github.com/nus-cs2030/2324-s2/assets/142781724/6bd61d8d-6c74-48aa-85cd-f395a3cb53e6">

**Comment by JosiahPraeman** [comment]
I faced the same issue with you for this test case and it might be because your self checkout queue is full when it is not supposed to be so u can go back and see your self-checkout logic. Perhaps since the issue lies with self check counters after the first self check, one logic which you can consider is that you need to always link back to your first self check to see if there is customers in the queue then you need to serve them first so that they do not leave the queue.

**Comment by zuoshihua** [comment]
If there is no self checkout available, customer should wait for the soonest available checkout i.e. the one with the earliest possible time that it will be done.

[#361](https://github.com/nus-cs2030/2324-s2/issues/361)

**Comment by jiancheng37** [comment]
this could be because your self-checkout logic might be flawed, check whether ur customer waits at the selfcheckout w the earliest available time or check how u handle the checkout being full ornot

**Comment by jpowcm** [comment]
i had the same issue, i think need to check why there is no serve event created for customer 13 at 0.862 (probably need to check the generation of serve from wait class) even though the server is alr available at 0.862 and customer 13 is first in queue

**Comment by timothyngcy** [comment]
thanks for d help everybody! let me try it out!
