### ISSUE TITLE
Return Type of Mapper Function

### ISSUE THREAD

**Issue by x2qian** [nus-cs2030/2324-s2#409]
hi does anyone know why the return type of Function has to be this and not just 'R' in <> since they both produce the same output for all test cases. 

thanks!

<img width="271" alt="Screenshot 2024-04-01 at 6 02 56 PM" src="https://github.com/nus-cs2030/2324-s2/assets/160982453/aee84b0e-d1be-48f5-8fce-53db4e11e42f">

**Comment by niclow236** [comment]
The issue here is with the return type of the Function parameter and the expectation of it to return a Log<R>. Function<? super T, Log<R>> won't work but it should be Function<? super T, ? extends Log<? extends R>> instead.

? extends Log<? extends R> allows the function to return a Log or any subtype of Log that extends R, which is important for flexibility. The flatMap method wants to accommodate mappers that might return Log<R> or any subtype of it. If you constrain it to Log<R>, you might lose out on the ability to use mappers that return subtypes of Log<R>.

By allowing the mapper function to return Log<? extends R>, you're providing flexibility. For example, if R is String, the mapper function can return Log<String>, Log<Object>, or any subtype of Log<String>.

However, if you restrict it to Function<? super T, Log<R>>, you are saying that the mapper must always return exactly Log<R>. This might not always be the case, and it can limit the flexibility and utility of the flatMap method.

**Comment by jarrenoh** [comment]
the return type of the flatMap method is actually still Log<R> 
what you are looking at is the parameter for the Function that flatMap takes in. In the end flatMap still returns objected assigned to Log<R> but its able to be mapped to/ work with subclasses of R because of the ? extends Log<? extends R>

**Comment by zuoshihua** [comment]
Return type and method parameter type are two different concepts. Please don't mix them up

**Comment by x2qian** [comment]
^^ ohh i see thank you all!
