### ISSUE TITLE
Help modifying flatMap so I am able to pass the last test case

### ISSUE THREAD

**Issue by ArkAzrael** [nus-cs2030/2324-s2#423]
# Summary

Modified f(int n) so it works but fails the last test case as it is calling one more flatMap than is needed on f(1)

## Description:

I had issues appending "1" to my output so I had to force it by flatMapping Log.of(1,"1") but it appears to be unnecessary. I believe my issue arises from how I implemented flatMap. Would like to ask for some help with correcting flatMap.

![flatmaptostring](https://github.com/nus-cs2030/2324-s2/assets/157274977/3fbc3bdc-a1ff-4eb8-af1c-a65d20b25c95)
![fint](https://github.com/nus-cs2030/2324-s2/assets/157274977/f6f99b0c-4f5e-4fe0-b5a2-5f7a0b98f5bd)

current implementation is above. I added checks to flatMap to handle the cases where the functions are identity functions to pass the monad test cases but it seems to be wrong. I am unable to get "1" simply by returning Log.of(1,"1").

**Comment by joshualek09** [comment]
hi arkazrael, you may refer to this issue thread as nicole had a query about flatmap(): 
[](https://github.com/nus-cs2030/2324-s2/issues/421)

i shall js copy paste my response here: 
hi nicole, yes, by doing Log<? extends R>, mappedLog can be a Log object with type R or any subtype or R.
this goes back to how conceptually, when you perform map you want to convert Maybe type T to Maybe type R. (Lecture 7)

So if you decide not to use bounded wildcards(? super / ? extends), then the types that flows in (T) and flows out (R), must match exactly. Otherwise, invariance occurs.

In your current code, i also see that the implementation of flatMap does not consider

if this.log is empty
else if mappedLog.log is empty.
additionally, you may want to adjust your return statement slightly, so as to make use of the .of() method.
for instance, in scenario 1 where this.log is empty, the code will look like

if (mappedLog.getLog() == "") {
            return Log.<R>of(mappedLog.getT(), this.log);
}
this statement check the log of the current Log and mappedLog. If the log of mappedLog is empty, it returns a new Log with the value of mappedLog and the log of the current Log object

scenario 2 will be pretty much the same in structure, just slightly change the condition and the parameters of the return .of()

your current return statement can be the else scenario. after this you should be good to go for flatMap()


next, for your f(int n),
firstly, declaring variables like int ONE, int TWO is not necessary if the goal is to write clean code. f(int n) already means n is an integer, hence more than half of the code block can just look like: 
```
Log<Integer> f(int n) {
    if (n == 1) {
      return Log.<Integer>of(1, "1");
   } else if (n % 2 == 0) {
      return Log.<Integer>of(n/2, n + " / 2").flatMap(x -> f(n/2));
    } 
```
the last part will be for the 3n+1 part, u should already be able to do it from the code preview above

**Comment by lifrocszh** [comment]
i think writing x -> f(x) is making it map to itself?

**Comment by mChewWW** [comment]
your generics for flatmap is wrong. it may work now but it will fail on codecrunch

**Comment by zzhengweii** [comment]
yup you to try implement your flatmap differently 

maybe you can try public <R> Log<R> flatMap(Function<? super T, ? extends Log<? extends R>> mapper) {
        Log<? extends R> logR = mapper.apply(this.item);
        if (this.log == "") {
        then return  Log.<R>of( smth)

**Comment by jesgiveup** [comment]
i saw someone say use:
public Log flatMap(Function<? super T, Log<? extends R>> mapper)

but it didnt work for me. there is return type error because the function provided to `flatMap` does not match the expected signature

I changed it to 
public Log flatMap(Function<? super T, ? extends Log<? extends R>> mapper) {

and it worked! Adjusting the function to exactly match the `flatMap` method's expected generic type parameters resolves this type mismatch.
