### ISSUE TITLE
Lecture 10 related question

### ISSUE THREAD

**Issue by niclow236** [nus-cs2030/2324-s2#434]
# Description
Hi, may I ask what does the number (3,3,5) in the return value of Thread.currentThread.getName() mean? Thanks!

## Screenshots
![IMG_20240403_190942_786](https://github.com/nus-cs2030/2324-s2/assets/156642018/cbde74c7-a2fd-48eb-a2e7-1da8f650e6be)

**Comment by IYKYKY** [comment]
it uniquely identifies the worker thread in the ForkJoinPool, to help understand of how concurrent tasks are managed and executed.(cf2 is directly chained to cf1 using thenRun(), which means cf2 will execute immediately after cf1 on the same thread. however, cf3 use thenRunAsync(), which means it will run asynchronously, so that the worker thread is different) Also, notes that thread could be reused, so the number u see in one execution may differ in another due to reuse and the dynamic state of the thread pool at the time of execution.

**Comment by niclow236** [comment]
> it uniquely identifies the worker thread in the ForkJoinPool, to help understand of how concurrent tasks are managed and executed.(cf2 is directly chained to cf1 using thenRun(), which means cf2 will execute immediately after cf1 on the same thread. however, cf3 use thenRunAsync(), which means it will run asynchronously, so that the worker thread is different) Also, notes that thread could be reused, so the number u see in one execution may differ in another due to reuse and the dynamic state of the thread pool at the time of execution.

Oh I see thank you!
