### ISSUE TITLE
Lab 6 Test Case 4 

### ISSUE THREAD

**Issue by allis-g** [nus-cs2030/2324-s2#446]
# Summary

Hi, has anyone else come across this error in output on Codecrunch?

## Screenshots

<img width="1353" alt="Screenshot 2024-04-05 at 10 34 10 PM" src="https://github.com/nus-cs2030/2324-s2/assets/161267008/0dd1b229-116a-4c4b-ad5b-821a3d4b409d">

**Comment by SumitShinde0702** [comment]
Hi, I think there might be something wrong in the logic which handles whether to print . or x. Could we see your code for the gameoflife method?

**Comment by kubrian** [comment]
You could check the following two potential sources of error.
1. As mentioned above, issue might lie in mapping from 0/1 to "." or "x".
2. Issue might be with the logic in your UnaryOperator. After one iteration, a given position should be 1 if it was 0, **and**, **only one** of its neighbours was 1. It should be 0 otherwise.

**Comment by hanlinnnnn** [comment]
u could check ur generateRule() first, it should return a function that takes in a list and outputs a new list of integers, following the rules stated in the index.pdf. observe if the function works by trying generateRule().apply() on an arbitrary list.

if that works fine then the issue prolly lies with mapping from numeric to . and x

**Comment by kohtw** [comment]
1. The logic for an alive cell dying the next round is not implemented correctly, to check. turn your stream into an array using .array()
2. The 1 and 0 is not correctly mapped to "x" and ".".
