### ISSUE TITLE
Lab 6: Level 4 

### ISSUE THREAD

**Issue by Slyriss** [nus-cs2030/2324-s2#450]
# Summary
Not sure where the issue with my logic is? 
Description of the question / problem here.

## Description:
Using the UnaryOperator generateRule(), everytime I run my code, it just ends up like the bottom, does anyone know why? 

## Code Snippets

Attach code snippets (if any)

## Screenshots
![image](https://github.com/nus-cs2030/2324-s2/assets/118103541/f31d71b9-5254-4e1c-95ba-8836a88c7e6e)

![image](https://github.com/nus-cs2030/2324-s2/assets/118103541/f6f8895f-5052-4cb4-b5e8-8c1c8b03f2b1)

Screenshots (if any)

**Comment by LimZiXiong** [comment]
There are few things you need to check. I would suggest to abstract out the checking by declaring another function since there's quite a few thing to check. If index == 0, check if right of itself is 1 if so 1 else 0. Similar if index == list.size() - 1, check the left is 1 if so 1 else 0. Other wise, check if left and right is 1, if so 0 else 1.

**Comment by gnimnix** [comment]
By your logic, both neighbours must be alive for it to be alive in the next generation. But the question states at most 1 neighbour alive.

**Comment by weikiatt** [comment]
i think you need to change the return statement line, instead of putting &&, use || because only 1 neighbour needs to be alive. alternatively, you could do left + right == 1

**Comment by hanlinnnnn** [comment]
u could try to use the xor operator ^ to ensure only 1 neighbour was alive

**Comment by RatesLearner** [comment]
i had the same issue, If the index is at the beginning of the list, verify whether the element to its right is 1; if it is, return 1, otherwise return 0. Similarly, if the index is at the end of the list, check if the element to its left is 1; if it is, return 1, otherwise return 0. Otherwise, examine if both the left and right elements are 1; if they are, return 0, otherwise return 1.

**Comment by lifrocszh** [comment]
i just did: 
- check if alive, return 0
- check if first index AND next one is alive, return 1, else return 0
- check if last index AND previous one is alive, return 1, else return 0
- check if (prev is alive AND next one is not) OR (prev is not AND next one is alive), return 1
- return 0

hope this logic helps!

**Comment by ZHD1987E** [comment]
Did it work @Slyriss? If you find them useful and it helped you solve your issue, you might want to close this issue to declutter the forum. Thank you!
