### ISSUE TITLE
Lab 6 lvl 3

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#454]
There is an error in the occurence count for my level 3 method any way to rectify this?

![Screenshot 2024-04-06 190457](https://github.com/nus-cs2030/2324-s2/assets/111676024/eefd9556-c74a-4c62-98e6-78820a0c2968)

![Screenshot 2024-04-06 190256](https://github.com/nus-cs2030/2324-s2/assets/111676024/99b552dc-8855-4546-9571-91d949d7db76)

**Comment by nicklass8** [comment]
hi the problem is that your are double counting instances where there are more than 2 repeated elements adjacent to one another (e.g. 0,0,0). To get around that, you need to implement another check in your filter method to ensure that the element you are checking is at the start of a repeated sequence and not in the middle or end of the sequence to avoid double counting which is what is causing this error. How I did it was .filter(i -> list.get(i) == list.get(i + 1) && list.get(i) != list.get(i-1)) Hope this helps!

**Comment by JosiahPraeman** [comment]
> nicklass8

i did this but now i face and outofbounds exception issue and i used intstream.range(0, list.size() -1)

**Comment by nicklass8** [comment]
you can try intstream.range(0, list.size() - 2) instead

**Comment by JosiahPraeman** [comment]
> you can try intstream.range(0, list.size() - 2) instead

There is still an out of range error

![Screenshot 2024-04-06 202638](https://github.com/nus-cs2030/2324-s2/assets/111676024/38493252-bd1a-4011-a055-6da1cfc4b234)

![Screenshot 2024-04-06 202714](https://github.com/nus-cs2030/2324-s2/assets/111676024/279cfe75-a2a5-4eaa-9995-cc7f68b130ef)

**Comment by nicklass8** [comment]
wait sorry it should be IntStream.range(0, list.size() - 1) but when x = 0, it checks index (x-1) which is -1 which causes the index error.

**Comment by JosiahPraeman** [comment]
> wait sorry it should be IntStream.range(0, list.size() - 1) but when x = 0, it checks index (x-1) which is -1 which causes the index error.

then how to rectify this

**Comment by nicklass8** [comment]
Can consider using a ternary operator

**Comment by allis-g** [comment]
hi, I did it by checking for x and x+2 and setting a new boundary for x+2, don't think its the best implementation but it works!

**Comment by JovanFoo** [comment]
what i did was i did a check for x-1 and x+1 from range (1,n) and i did another check to cater for only (0,1). not the best but it works
