### ISSUE TITLE
Lab 6 Task 4 Extra Case

### ISSUE THREAD

**Issue by hadyamanisanto** [nus-cs2030/2324-s2#462]
On CodeCrunch, i received this error, 
<img width="972" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/794a976b-189f-45b4-b6a6-eef6e1012e68">

Here is my code, which includes a helper function:
<img width="448" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/158229622/1cf469bc-3111-4b64-9d92-0636934682aa">

Any more conditions I have to consider?

**Comment by gnimnix** [comment]
The test case is calling `Test4.doit()` and not using the default `generateRule()`. Check your `gameOfLife()`, are you explicitly calling your default `generateRule()`?

I see that you are also using the bitwise XOR operator. Consider simplifying your code to `return left ^ right` where `left = list.get(i -1 )` and `right = list.get(i + 1)` and they are `0` if they are out of bounds.

**Comment by cth06-Github** [comment]
Hmm I am not too sure what is wrong but I will share what I think (take it with a pinch of salt just in case I am wrong!):
Logic wise I will say you have considered all conditions for the unary operator...pretty sure when I write my code I only thought of these. 

<img width="594" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/106983097/7b2a5ddd-c1f2-44e3-bc1e-0f096e51c365">
^^but from the test output you have attached, from line 1 [95] to 2 [96], the middle x should die and become a dot if we are to follow the rules indicated by generateRule(). But it did not. Also, In this test case, the arguments passed into the function is slightly different where the rule governing the Game of Life is called `Test4.doit()`. I am thinking whether this test case has used a different set of rules.

So I am thinking the issue lies in how you have defined the `gameOfLife(List<Integer> list, UnaryOperator<List<Integer>> rule, int n)`. You may want to check that! Even if there are no issues, then maybe it is also how the generateRule is defined too [like it can be correct, but because of the implementation is slightly different, the implementation that we have is unable to handle any modifications the test case has...? not too sure but I have this conclusion based on my experience with another lab). Though comparing the code you have and mine, I think the issue lies in gameOfLife() function?

In the spirit of functional programming, I also suggest considering using map() when converting from number to string too (referring to the static helper function convert)! That mapping function can be placed somewhere in the gameOfLife() function.

**Comment by ZHD1987E** [comment]
That’s what happens if your rule function is completely screwed up…

You might want to look at your code again and see what you can do.

**Comment by ZHD1987E** [comment]
Alright.

it does seem that your code is quite inflexible when I pass on a new rule. That means you will have to check your gameOfLife function and see if you have hardcoded any rules.

**Comment by hadyamanisanto** [comment]
Fixed it. Thank you!
