### ISSUE TITLE
Java Import Issue

### ISSUE THREAD

**Issue by Hjkiiiim** [nus-cs2030/2324-s2#481]
I've encountered an issue when importing Java packages (for example, import java.util.Scanner; and import java.util.List;) into my projects. I noticed that these imports do not seem to be compiled or are not working as expected in JShell, while they work fine when I'm coding in Vim. Could there be a specific reason why imports behave differently in JShell compared to Vim?

**Comment by ZHD1987E** [comment]
JShell likely has everything from the utility package imported

**Comment by YogeshJavaTech** [comment]
If you're experiencing issues with importing Java packages in JShell, there could be a few reasons why it's not working as expected:

1. **Classpath Configuration**: JShell might not be able to locate the Java packages because the classpath is not properly configured. Ensure that JShell is aware of the location of the Java standard library and any additional libraries you're using.

2. **Module System**: If you're using Java modules (introduced in Java 9), you need to ensure that the modules containing the packages you're trying to import are accessible to JShell. You might need to specify the module path or add the appropriate modules to the module path.

3. **JShell Configuration**: Check if there are any specific configurations or options that need to be set in JShell to enable importing external packages. You may need to specify additional options or flags when launching JShell.

4. **Syntax Errors**: Ensure that there are no syntax errors in your import statements or other parts of your code. Even a small typo or mistake in syntax can prevent the import statements from working correctly.

5. **JShell Version**: Ensure that you're using a compatible version of JShell with the Java version you're targeting. Newer Java versions might have different behavior or requirements for importing packages.

To troubleshoot the issue further, you can try the following steps:

- Check the JShell documentation or online resources for guidance on importing external packages.
- Experiment with different import statements and try importing packages from different locations to see if the issue persists.
- Verify that the Java packages you're trying to import are accessible and correctly installed in your Java environment.
- Double-check your classpath and module path settings to ensure they are correctly configured.
- If you're still unable to resolve the issue, consider seeking help from forums, online communities, or consulting with colleagues or experts familiar with JShell and Java development.

**Comment by ZHD1987E** [comment]
@hwkchia We have an invader…

**Comment by ZHD1987E** [comment]
@YogeshJavaTech Did you reach the wrong repository?

**Comment by ZHD1987E** [comment]
@Hjkiiiim I hope your issue has been resolved. If so, you might want to close the issue. Thanks!
