### ISSUE TITLE
Project Test Case 3: servers not resting

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#488]
# Summary
Put a summary of the question

## Description 
Servers are not resting properly. Im not able to pass the public test case and my output for the protected test case is attached below as well.

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/5705cd00-2141-42a9-aed2-678e044dbf35)
![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/bad7f4f0-6435-4db3-9097-05027ea91194)

**Comment by zi-yii** [comment]
Maybe you could check if you have updated the queue of servers properly? your line 30 output says 12 is added to queue of server1, but afterwards, 9,10,11 were served by 1 which implies 9,10,11 were already in queue of server1 when the max queue should be 2

**Comment by Darren-chan-jr** [comment]
I think you may not be calling the most updated server list when you get your server, which could explain why your customers aren't waiting at the right server. Another thing to note would be the resting of your servers, currently they dont seem to be resting, what you could do is to add some print statements to print out the rest time and rest end time and check whether it corresponds with the output

**Comment by pramoth20** [comment]
I believe there might be an issue with your serve and done serving class depending on you implementation. try to check if you have been updating the ImList of servers of whether they are available or not properly

**Comment by weiyangng** [comment]
ok pramoth20 @pramoth20

**Comment by naomiiiwu** [comment]
Hi may I know if u managed to solve the problem? cuz Ive encountered similar issues.

**Comment by ccqie233** [comment]
maybe you can check the implementation of WaitAgain event execute method and see whether the returned event uses the most up-to-dated availableTime of the server. 

I faced the same issue. In my doneEvent, the next availableTime was correctly updated to 5.9 something. It was not used by the execute method in my WaitAgain event: when WaitAgain of customer 6 at 5.053 was executed to return a new WaitAgain of customer 6 at supposedly 5.9, it did not use the most recent availableTime

The second error may come from where you update your customer queue? maybe you can try update the queue in serveEvent instead of when waitAgain is executed to return a serveEvent (not sure about your implementation)

**Comment by weiyangng** [comment]
my issue is some where along those lines as the rest time in my done event is not being trigger as a result my program adds the servicetime before it adds the rest time which is causing server 6 to get the rest time instead of server 5

**Comment by nicthepurplejelly** [comment]
hii! What i did it was that I added the rest time in my Done event, perhaps you could take a look at your Done event again to ensure that your rest time is properly added to the respective servers?
