### ISSUE TITLE
Exercise 5 Maybe-- What's the difference between these two? 

### ISSUE THREAD

**Issue by naomiiiwu** [nus-cs2030/2324-s2#492]
<img width="491" alt="Screenshot 2024-04-09 at 12 12 51 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156983070/42c4161b-69c2-47be-9e12-e715815cb21e">
Hi 
May I know why the first one works but the second one does not? 
Is it because there is no guarantee that supplier.get() will return a Maybe, so no guarantee that there is a get() method?

Also for the first one, why is it possible to use result.get() when get() is a private method? Or am I confused on how to use the private getters?

**Comment by naomiiiwu** [comment]
Also is it wrong to write the following:
Maybe<T> result = supplier.get();

Instead of
Maybe<? extends T> result = supplier.get();

why?

**Comment by naomiiiwu** [comment]
Also is it wrong to write the following:
Maybe <T> result = supplier.get();

Instead of
Maybe<? extends T> result = supplier.get();

why?

**Comment by iceflakes12** [comment]
1. Second one doesnt work because your supplier.get() is a subclass of Maybe so there is no guarantee that you will be able to access the get() method since the get method is private. First one works because you read supplier.get() as a Maybe object so now the compiler treats it as a Maybe instead of a subclass of Maybe.

2. It is possible to use result.get() because get() belongs to Maybe class so you can call the get methods of other objects that belong to the Maybe class also

3. You cannot write Maybe<T> because Maybe<T> is not a superclass of Maybe<? extends T>

**Comment by naomiiiwu** [comment]
> * Second one doesnt work because your supplier.get() is a subclass of Maybe so there is no guarantee that you will be able to access the get() method since the get method is private. First one works because you read supplier.get() as a Maybe object so now the compiler treats it as a Maybe instead of a subclass of Maybe.
> * It is possible to use result.get() because get() belongs to Maybe class so you can call the get methods of other objects that belong to the Maybe class also
> * You cannot write Maybe<T> because Maybe<T> is not a superclass of Maybe<? extends T>

okay thank you got it!
