### ISSUE TITLE
Lab 5 test case  5_1

### ISSUE THREAD

**Issue by sje5398p** [nus-cs2030/2324-s2#493]
My code works on jshell, but for some reason it fails in the last test case. Does anyone know why? Thanks!

[](url)
<img width="535" alt="Screenshot 2024-04-09 at 1 54 15 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/9e4927a5-818c-46cc-8ec5-986ae9de1d61">

<img width="186" alt="Screenshot 2024-04-09 at 1 54 55 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/6c0c8d64-76e8-4295-a959-9be28aecb756">

**Comment by linguinyi** [comment]
#412 mentioned this issue too, you can try checking to see if your flatMap matches
Log flatMap(Function<? super T, ? extends Log<? extends R>> f)

**Comment by sje5398p** [comment]
thank uu!

**Comment by RatesLearner** [comment]
Face the same error, posted on another thread here goes :

The difference between public Maybe or(Supplier<? extends Maybe<? extends T>> supplier) and public Maybe or(Supplier<Maybe<? extends T>> supplier) lies in the flexibility of the Supplier parameter. In the first method signature (public Maybe or(Supplier<? extends Maybe<? extends T>> supplier)), Supplier<? extends Maybe<? extends T>> means that the supplier can provide any subtype of Maybe<? extends T>. This allows for more flexibility in the types of Maybe instances that the method can accept as arguments. However, in the second method signature (public Maybe or(Supplier<Maybe<? extends T>> supplier)), Supplier<Maybe<? extends T>> restricts the supplier to only provide instances of Maybe<? extends T>. This is less flexible because it requires the exact type specified by the method signaturethis, otherwise logic looks correct.

**Comment by Xenonwizard** [comment]
I think you can try tweaking the wildcards for your flatMap.
