### ISSUE TITLE
Test Case 9_9

### ISSUE THREAD

**Issue by jianhaosoh** [nus-cs2030/2324-s2#504]
What could be the possible issue for this? For my waitEvent and serveEvent's toString method, I included and if-else as well which will return a "...serves by self-check..." if it is a self-check counter but it does not seem to be reflected in the output

![Screenshot 2024-04-10 at 10 25 13 AM](https://github.com/nus-cs2030/2324-s2/assets/142876316/e27acc6a-5eb3-4cef-b7e1-9bf2ca4c2ec7)

**Comment by delulu04** [comment]
hi! i faced a similar problem, but i am not sure if your implementation is the same as mine. 
for me, my SCC was a subclass of server. so every time i update my server queue or available time, i had to create a new Server/SCC. however i had forgotten to create a new SCC when i updated SCC, instead creating a new Server instead so my toString() did not reflect "self-check .."

**Comment by feliciahmq** [comment]
hi :) if ur SelfCheck extends Server, then SelfCheck should override any functions in Server if the function creates a new instance of Server. This ensures that when SelfCheck is instantiated, its declared as SelfCheck specifically and the toString method of SelfCheck is invoked instead of Server. hope this helps!

**Comment by yishao17** [comment]
hi! had similar issues at the start. what i realised was in 1 of my methods, i created server instead of self check out when its supposed to be self check out! 
i solved the issue by making server an abstract class and having a HumanServer and SelfServer class that extends it then override the methods that create new instances of server! hope that helps :)

**Comment by nicthepurplejelly** [comment]
hii! similar to @yishao17, I also faced this problem before as I created server instead of SCCs, so maybe you would want to check on that!!

**Comment by jianhaosoh** [comment]
Thanks for the help!
