### ISSUE TITLE
Passed all test case for human server (up to 3.in) but kena cyclic dependency error

### ISSUE THREAD

**Issue by jiayingtjy** [nus-cs2030/2324-s2#508]
## Description:
![Screenshot 2024-04-10 125100](https://github.com/nus-cs2030/2324-s2/assets/144901924/9a7dda0c-d056-41de-93e9-71459054ba2c)

i figured out the reason for the cylic dependecy  
this is the flow : 
1. ARRIVE → SERVE → DONE -> REST --> RESTEND --> might return SERVE 
2. ARRIVE → WAIT → SERVE → DONE -> REST --> RESTEND --> might return SERVE 

cyclic dependency occurs when the LAST event might be returning a new event (which causes a loop int the events)

**but how should i solve this problem whereby i am not allowed to continue an event while ensuring that the serve is being determined after the rest**
if determine the serving event during the wait event  it may miss out on wait time because there could be additional rest event after server is done serving but i have already created serve event with the wrong timing before that

Any kind souls pls help ://

**Comment by delulu04** [comment]
hi! maybe instead of a rest event you can just update everything in done?

<img width="670" alt="Screenshot 2024-04-10 at 1 36 51 PM" src="https://github.com/nus-cs2030/2324-s2/assets/155940515/c8499f1f-1a52-48a0-808b-545940635b49">

what i did was to call server.getRestTime() in Done, and then update the serverAvailableTime and then set this updatedServer into the serverImList. regardless of whether ur restTime is 0 or more than 0, this should then work! hope this helps!

**Comment by gnimnix** [comment]
I am guessing you are returning `ServeEvent` after `RestEndEvent` to get the next customer to the server?

What you can try is at the end of each event in your `Simulator`, check which servers are free to serve the next customer and create a `ServeEvent` there.

Essentially, extract the logic from your `RestEndEvent` and put it in your `Simulator` to get rid of the cyclic dependency.

**Comment by jiayingtjy** [comment]
@delulu04 @gnimnix 
thanks i have managed to solve this!!
