### ISSUE TITLE
Project Test Case 11

### ISSUE THREAD

**Issue by yishao17** [nus-cs2030/2324-s2#514]
# Summary
how do I make sure that they look for the right checkout counter to go to? and this 2 test cases shows different kind of error
1. getting served by the wrong server 
2. getting served instead of waiting 

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
<img width="818" alt="Screenshot 2024-04-11 at 2 16 08 AM" src="https://github.com/nus-cs2030/2324-s2/assets/158052429/d4c5d7f6-00fc-4e39-bf8f-b2fdb8a9f10b">

<img width="646" alt="Screenshot 2024-04-11 at 2 15 40 AM" src="https://github.com/nus-cs2030/2324-s2/assets/158052429/809503f3-1b95-48e3-b9a6-7b6c67c7f30d">

**Comment by vanesssalai** [comment]
Hi it seems to me you have an issue in updating your self checkouts wait list/ availability updating. You can check how your scc updates the wait list/ service of the customers in the wait list and available time when the customer is served.

**Comment by MarcusLiangg** [comment]
Hi, in your wait event, update the self-checkout server by finding the next minimum available time by going through all the self-checkouts

**Comment by nicklass8** [comment]
Hi I actually got the exact same problem as you. Turns out for one of my loops to update all my self checkout counter queues, i missed out on a Server oldServer = serverList.get(i - 1). You can refer to the picture that I have attached for reference. If you still havent resolve this issue maybe you can try looking through all your selfcheckout loops to see if you missed out on the statement like me. Hope this helps!
![Uploading Screenshot 2024-04-11 at 3.00.36 PM.png…]()

**Comment by nicklass8** [comment]
Hi I actually got the exact same problem as you. Turns out for one of my loops to update all my self checkout counter queues, i missed out on a Server oldServer = serverList.get(i - 1). You can refer to the picture that I have attached for reference. If you still havent resolve this issue maybe you can try looking through all your selfcheckout loops to see if you missed out on the statement like me. Hope this helps!
<img width="463" alt="Screenshot 2024-04-11 at 3 00 36 PM" src="https://github.com/nus-cs2030/2324-s2/assets/163880002/b2188be1-156e-49d6-9197-42595ea6313a">

**Comment by IYKYKY** [comment]
Need to find the soonest available self-checkout counters. I write it in Wait Event so that when scc-4 is free, 13 will be served by 4 instead of keep waiting at scc-3 (but remember to update queue and scc next available time correctly)
