### ISSUE TITLE
Project test case 3 -- different return value for indexof and serverID - 1

### ISSUE THREAD

**Issue by naomiiiwu** [nus-cs2030/2324-s2#517]
Hi anyone has this issue? When I try to print out these two , they turn out to be different. Sometimes it returns -1 for indexOf but I don't know why. Are they not supposed to be the same?

**Comment by vanesssalai** [comment]
I had the same issue and its because you may have updated the server in your code which means its no longer the same instance of server and not in the server list hence will return index of -1. It depends on your inplementation but a general implementation can be calling your Server server = serverID - 1 and update frm there

**Comment by vanesssalai** [comment]
Or the server was updated in another event

**Comment by naomiiiwu** [comment]
tks I got it!
