### ISSUE TITLE
Project Test Case 9_11 Time Limit Issue

### ISSUE THREAD

**Issue by bbxg16** [nus-cs2030/2324-s2#524]
# Summary
Time limit exceeded for test case 9_11

## Description 
I suspect that the problem is related to my MoveUpQueue (which is an event after Wait and handles the customers in the queues). I have a while loop to find the earliest serviceTime of all selfCheck counters (which seems to work fine) and the problem may be related to always returning MoveUpQueue instead of Serve. I do not know how to debug for this. Anyone can give me some suggestions on debugging or some test case samples that I could use tackle this problem? 

## Screenshots (if any): 
<img width="608" alt="Screenshot 2024-04-12 at 11 22 12 AM" src="https://github.com/nus-cs2030/2324-s2/assets/160305895/e7f7a741-6597-4df8-a3e2-3a20ba3cdbcb">

The last part of the nextEvent in MoveUpQueue with the conditions of returning Serve
<img width="704" alt="Screenshot 2024-04-12 at 11 30 15 AM" src="https://github.com/nus-cs2030/2324-s2/assets/160305895/8d9ad85c-0316-4a05-962e-c979af5fc0bb">

**Comment by yishao17** [comment]
Hi, idk if my error is the same as urs but I got TLE error too. What I realised is my Hold (same idea as ur MoveUpQueue) cant move to a serve event, even though the timing changed so it kept returning another Hold event of the same timestamp, hence leading to infinite loops. What I did was to add in print statements in my execute method of all event class and run the test case locally. It will show which part keeps executing and from there, u can see which method is wrongly implemented/ logic error

**Comment by ThamudayaWinBerry** [comment]
you can try this test case which I crafted for 9_11:

0 3 1 0
0.000000
0.300000
0.700000
0.800000
0.900000
1.000000
1.100000
1.200000
1.300000
3.900000

Expected output:
0.000 1 arrives
0.000 1 serves by self-check 1
0.300 2 arrives
0.300 2 serves by self-check 2
0.700 3 arrives
0.700 3 serves by self-check 3
0.800 4 arrives
0.800 4 waits at self-check 1
0.900 5 arrives
0.900 5 leaves
1.000 1 done serving by self-check 1
1.000 4 serves by self-check 1
1.000 6 arrives
1.000 6 waits at self-check 1
1.100 7 arrives
1.100 7 leaves
1.200 8 arrives
1.200 8 leaves
1.300 2 done serving by self-check 2
1.300 6 serves by self-check 2
1.300 9 arrives
1.300 9 waits at self-check 1
1.700 3 done serving by self-check 3
1.700 9 serves by self-check 3
2.000 4 done serving by self-check 1
2.300 6 done serving by self-check 2
2.700 9 done serving by self-check 3
3.900 10 arrives
3.900 10 serves by self-check 1
4.900 10 done serving by self-check 1
[0.129 7 3]

I also faced this infinite loop error and after inserting print statements, I realised the error was in my isAvailable() method for self check out counters and this was because I was comparing the self check out available time with the customer's arrivalTime instead of the currentTime, which led to the self check out counters never being available and hence the Wait events keep returning after one another. Hope this helps :).

**Comment by bbxg16** [comment]
Thank you guys! The problem is related to my wait class (which is returned after arrive). The time for the nextEvent in wait class is wrong: I used the sever's next available time (which is not working for self check counter) After I change the time to the time of the wait event, it works. For anyone who may read this, use the test case above and write a print statement for each class to check what's going on (especially when the self check service ends at the same time as a new customer come) :)

**Comment by Yiting55** [comment]
thanks! I also encountered the same problem, really helped me to debug!
