### ISSUE TITLE
How do I display colours on terminal (Macbook 13.6.1)

### ISSUE THREAD

**Issue by craezydodo** [nus-cs2030/2324-s2#54]
# Summary
Hi all! My terminal is in black and white whenever I open vim xx.java, but it is colourful on my friends' screens. How do I go about setting it to display colours for keywords?

## Screenshots (if any): 
Insert Images here if necessary
<img width="755" alt="Screenshot 2024-01-29 at 4 43 36 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157350945/29b4585e-bb72-425c-a49a-151ee4fd8e64">

**Comment by yewyaorui** [comment]
maybe trying setting to dark mode? just a thought u can try it out because mine is on dark mode. hope that helps!

**Comment by jaslyntay** [comment]
have you tried restarting? maybe that'll help, cheers!

**Comment by ZHD1987E** [comment]
1: Did you have the `.vimrc` file installed correctly? They have an option for Syntax highlighting.

2: Did you enable colour settings on your terminal (if there is one)?

Sorry, I am a Windows Person...

**Comment by zuoshihua** [comment]
Do yourself a favour and install iTerm2

**Comment by reynardian** [comment]
I am a mac user, and I had a similar problem before; it was due to the vimrc file not being in the correct location. You can type :echo $MYVIMRC inside vim to open the vimrc that is being used. You can then just copy and paste the contents of the vimrc file provided in the Github wiki to this correct vimrc file.
