### ISSUE TITLE
MOCKPA2 LEVEL 3

### ISSUE THREAD

**Issue by itzsihui** [nus-cs2030/2324-s2#548]
# Summary
Put a summary of the problem here
my sub will return NaN if it is not a natural number, i think that is why i cannot pass test case, may i ask how can i solve my issue?

## Description 
Describe the problem and any details if neceesary

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
Insert Images here if necessary
<img width="685" alt="Screenshot 2024-04-13 at 11 15 47 PM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/09fe737e-ee8f-411c-acb7-0136cd20d6fe">

<img width="557" alt="Screenshot 2024-04-13 at 11 15 58 PM" src="https://github.com/nus-cs2030/2324-s2/assets/96379352/31f96d4d-8d50-465a-b8e0-e4b1e01fb16a">

**Comment by LimZiXiong** [comment]
Hmm when you do new Num(other.opt.map(n)) you are negating the value here. So your Num is actually invalid hence doing .add on an invalid number also results in an invalid number

**Comment by itzsihui** [comment]
ohyaaaa, thank you !!

**Comment by itzsihui** [comment]
then may i ask how can I  get around it?

**Comment by LimZiXiong** [comment]
> then may i ask how can I get around it?

Did you filter the Optional for the constructor taking in Optional? Since all constructor should be private i think it's ok to not check the Optional when using constructor. But to be safe what i did is do what I did on addition. I negate the Optional and keep calling succ until my Counter optional is equals to the Num that was passed in the argument

**Comment by iceflakes12** [comment]
Another way you can try:
you can also use add method of a negative Num since negative Num is not invalid until you invalidate it.
Basically in the question header they say -n.add(m) you can literally just copy it.

**Comment by ettenyll** [comment]
Hello, my sub method is exactly the same as yours and I got it to work after changing another method (so your implementation of sub should be okay). I put output statements in the add() method loop to check and realised that as long as the result was negative, it would return NaN (5 - 2 would still return NaN despite being positive because result = -1 after first pass of loop) and went about debugging from there.

**Comment by meowmeowpeepee** [comment]
i used a helper function to allow me to add without checking for the validity

**Comment by itzsihui** [comment]
thank you everyone !!
