### ISSUE TITLE
Project test case 11

### ISSUE THREAD

**Issue by sje5398p** [nus-cs2030/2324-s2#550]
<img width="584" alt="Screenshot 2024-04-14 at 12 13 18 PM" src="https://github.com/nus-cs2030/2324-s2/assets/164729773/1025e1c1-7d35-49c1-95eb-1a1bf394a5eb">

Hii, I know there is something wrong with the implementation of my scc queue, but if anyone has any specific feedback it would be very helpful! I have looked at my code too much so I can't really spot anything 

Thank u sm

**Comment by samuelneo** [comment]
customers waiting in the SCC queue should rewait at the minimum next available time out of all the SCCs. so 13 should have rewaited immediately after 9 was done serving so that 13 can transition from Wait -> Serve

**Comment by ThamudayaWinBerry** [comment]
I think the issue should be in the updating of nextAvailableTime.
you can try crafting your own test case with 0 human servers and the scenario where a new customer arrives at the same time as the doneTime of a customer at the self-checkout counter. then add print statements (especially just before the method where you transition from Wait to Serve) to track if the nextAvailableTime of the servers are as expected and debug from there.

**Comment by yishao17** [comment]
it seems that ur SCC does not serve the next in line customer (maybe ur customer waits at an allocated SCC instead of seeing which one has the shortest time). If you have a hold event, u should see how it moves from hold to serve or hold to hold! 
hold to hold: if it is a SCC, need to check all other SCC and update the timestamp to the earliest timeAvail of all SCCs
hold to serve: if it is a SCC, need to check all SCC, see which SCC's timeAvail corresponds to the timestamp of the hold before transitioning to serve of that SCC. 
hope this helps :))

**Comment by sje5398p** [comment]
thank you!! i'll try that :)

**Comment by wangjiakng** [comment]
hii im getting the exact same output as you do, have u figured it out

**Comment by nicklass8** [comment]
hello, i encountered this exact output before. If your implementation of the SCC queue is such that each SCC has a queue that is identical to the queues of the other SCCs and each time a customer is added or removed from a SCC queue, they are also added/removed from all other SCC queues, then this could be applicable for helping you debug you error. You can check to see if your loops to update all the SCC queues for the applicable events is correctly implemented (e.g. for each loop, replace each SCC with a new SCC whereby only the queue is different from the old SCC, everything else like finishTime remains the same). I got this error output because when I was replacing each SCC, I accidentally changed the finishTime of all SCCs to be the finishTime of the fastest SCC. Hope this helps!

**Comment by Violetloo** [comment]
hi i just solved this same output. it seems like your customer is still waiting for the specific SCC, when it should be waiting for any of the SCCs since they all share one queue. So for your wait/ hold event you should loop through all SCCs and see which SCC is already available.

**Comment by yxhi** [comment]
hi! i just solved this issue too, your customer need to check whether any of the SCCs are available every time the Wait event is called if it is in a SCC queue, while checking for the minimum available time among the SCCs and input it as your timeStamp when you transition into a Wait event. it might be easier to visualise having 2 cases of (when the server is human or a SCC), and handle the transitioning of events seperately :)

**Comment by sje5398p** [comment]
thank you everyone for all your help!!! much appreciated
