### ISSUE TITLE
Not sure how to put the Waiting Event that transitions to Serve Event, to come after Done Event

### ISSUE THREAD

**Issue by meowmeowpeepee** [nus-cs2030/2324-s2#554]
Project Test Case 3
double above is availableTime of server 1 , and bottom is that of 2
![image](https://github.com/nus-cs2030/2324-s2/assets/164331190/ec98fc4d-4139-48b7-ba7c-9d993ec3ced0)

As seen here, my 6th customer(in queue) gets his Serve Event before 5th customer finishes and Server 1 rests, since Waiting Event will return Serve Event for the next Customer in queue.  Hence, service time of 6 is the time 5 finishes and not after Server 1 rests
![Uploading image.png…]()

My idea is for Done Event to update server available time, and there is not rest Event, is my idea right or can i get a hint on how to ensure that a customer is served after Server is done resting

**Comment by vanesssalai** [comment]
Your idea is almost correct but when your server AvailableTime is updated in the done event you can consider how your customer in the waiting event should kind of "consider" again whether that particular server is available to serve

**Comment by yishao17** [comment]
^^ i think her comment is something u should consider. What I did (hopefully it helps) is, if it is a SCC, everytime u update the timestamp, u need to evaluate the list of SCCs again to find the earliest timeAvail/ server to serve. hope this helps! all the best :))

**Comment by ThamudayaWinBerry** [comment]
I did the same approach as you; not having a rest event. You can consider updating the server available time (i.e adding the rest time for human server) in simulator class instead of inside done class and reset the serversList that gets passed around with the updated server (assuming your approach was passing around the serversList instead of the customersList). Hope this helps. :)

**Comment by yishao17** [comment]
maybe something to add is to always check the timeavail against the timestamp and make sure that it is available to serve

**Comment by Yiting55** [comment]
I dont have rest event as well. instead of updating in the done event, I update server available time in serve event, but I think doing it in done event is also right. But you might review your wait event and design it such that only when the server is available, the next server gets served. this means that you may check the server's available time before returning the next serve event

**Comment by meowmeowpeepee** [comment]
managed to solve it, thanks guys, really appreciate it @ThamudayaWinBerry @Yiting55 @yishao17 @vanesssalai
