### ISSUE TITLE
mock pa2 compilation errors 

### ISSUE THREAD

**Issue by yminnnx** [nus-cs2030/2324-s2#562]
<img width="286" alt="Screenshot 2024-04-14 at 10 27 13 PM" src="https://github.com/nus-cs2030/2324-s2/assets/163486879/cd45d8d5-92b6-4a23-b283-b7c6c48d2af1">

hello may i ask how do i go about this and what r they referring to?

**Comment by heokieee** [comment]
hi, i think the problem would be that you have use methods that are not in the implementation for the optional class, please refer to the lect slides to see what you can use or not use!! hope this helps.

**Comment by Violetloo** [comment]
Hi, i believe there are restrictions in the prompt saying you you cant use some Optional methods, such as get() or orElse(), try avoiding them

**Comment by zuoshihua** [comment]
You should only need `of()` `empty()` `map()` and `flatMap()` from `Optional`

**Comment by citronwhitetea** [comment]
Hello! It appears there are specific constraints on the use of Optional methods in this scenario, likely due to particular implementation requirements or design considerations. To adhere to these restrictions effectively, focus on utilizing methods recommended by the lecture materials. These methods offer versatile ways to handle optional values without resorting to potentially restricted functionalities!

**Comment by meowmeowpeepee** [comment]
In your implementation, you are not allowed to use the Optional methods isPresent, isEmpty, or any form of get methods, i.e. get, orElse, orElseGet, orElseThrow.

**Comment by ZHD1987E** [comment]
Did you read #528? Check it out!

**Comment by yminnnx** [comment]
okay thanks all!
