### ISSUE TITLE
Mock PA2 Level 1 

### ISSUE THREAD

**Issue by allis-g** [nus-cs2030/2324-s2#575]
Hi, so Ill just like to ask what should I do to call the isValid() method for checking first before succ() cause i understand that isValid is not a static method but yet the call is succ() without parameters so im quite stuck here pls help thanks!

**Comment by euuren** [comment]
You can use Optional.map
This is from Java API 
public <U> Optional <U> map(Function)
If a value is present, apply the provided mapping function to it, and if the result is non-null, return an Optional describing the result. Otherwise return an empty Optional.
https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html

**Comment by zuoshihua** [comment]
1. `succ()` is not a static method
2. there is no need to call `isValid()` in `succ()`

**Comment by kaiju10** [comment]
to add on, in case you didnt do the check, you can use `AbstractNum.valid.test(value)` and it will return a true or false from there

**Comment by jwoongg** [comment]
succ() basically increases your num by one, isValid()checks if your optional contains a value

**Comment by juliannxe** [comment]
`succ()` would return `NaN` if the `isValid()` method returns `false` anyway

**Comment by Castelle-code** [comment]
> https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html

how do you do that when we cannot declare any private final fields and ur succ() does not take in any parameters

**Comment by Tianye0130** [comment]
Ensure isValid() is Accessible: Since isValid() is not static, you need an instance of the class to call it. Ensure you have an object instantiated from the class that contains these methods.

Create a Wrapper Method: If succ() must be called only after isValid() returns true, consider writing a wrapper method in your class that first checks isValid() and then calls succ() if valid. This way, you encapsulate the validity check and the subsequent operation in one method.
