### ISSUE TITLE
project wrongly generate restTime

### ISSUE THREAD

**Issue by Yuxin-Mellisa** [nus-cs2030/2324-s2#579]
when I put the probability of rest to be 0 it is fine
<img width="372" alt="Screenshot 2024-04-15 at 9 22 16 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157778558/ccacfb5f-7be1-491d-bdda-51c8bfc3c32c">

when I put the prob to be 0.5 it dies
<img width="209" alt="Screenshot 2024-04-15 at 9 22 47 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157778558/f621b133-e33f-4cdf-bd4d-f68cfd28c21b">
<img width="539" alt="Screenshot 2024-04-15 at 9 23 28 PM" src="https://github.com/nus-cs2030/2324-s2/assets/157778558/4ae95fa5-113f-493f-9b1b-84bd966df89e">
How does it happen? it means that my restTime is generating a negative number?

**Comment by Jeremythong2002** [comment]
Agree, would suggest to print out the server rest times so you can see what is happening. I think you need to double check how the done time is generated as well, there's seems to be some minusing of time going on

**Comment by KoalaLyfestyle** [comment]
I am having this issue as well, for this test case 1, I did System.out.println(restTime) and it gave me 1.0 instead of 0 for restTime.
 - Test case 1:
![image](https://github.com/nus-cs2030/2324-s2/assets/146793482/f551f7f8-1f9e-484b-a5ee-25759f659b2d)
 - Supplier.get location in Server (rest() only called once in Done event)
![image](https://github.com/nus-cs2030/2324-s2/assets/146793482/5d4d33ad-db32-4671-811e-faf792087726)
 - TC1 result:
![image](https://github.com/nus-cs2030/2324-s2/assets/146793482/2295d3c9-69e1-4fd4-97b9-67607f02aacf)
 - When removing rest() from Done event the TC1 result is correct
![image](https://github.com/nus-cs2030/2324-s2/assets/146793482/27f3c84d-14cb-4d3e-9659-ebf937224a01)

Anyone has an idea of whats going on? hahaha

**Comment by marvinchoo-mh** [comment]
it seems a potential place where it may have gone wrong lies in the updating of serverList like what brian said you might be updating the serverList with an outdated timings. you can try using System.out.println() the rest times with shorter test cases to narrow down on where it went wrong

**Comment by itsbrandonaw** [comment]
I agree that it maybe that your timing that you have gotten is not the most updated!

**Comment by JovanFoo** [comment]
i think you might not be updating your time correctly, maybe you can check whether you update the new updated time when you create the new event
