### ISSUE TITLE
Ungraded ex 2

### ISSUE THREAD

**Issue by MaverickWongKeJun** [nus-cs2030/2324-s2#597]
Been having issues with level4, managed to get the trace output correctly but ran into the issue that print() also outputs the trace. Anyone else encountered this issue and how did yall fix it

**Comment by samuelneo** [comment]
taking level 5 into account may help. each traceable step should do two things: update the current (lazy) String, and update the trace with the current step. `print` should make use of `run` which shouldn't be affected by updating the trace

**Comment by Jeremythong2002** [comment]
@samuelneo could I check how you stored the trace? Was it within an Optional<String>? Because I know that if you store it within a String CodeCrunch will reject it on the basis of dependency on String.

**Comment by samuelneo** [comment]
I stored it in a `Function<Consumer<String>, String>` (not my idea, got it from my TA), it's a really smart way to make sure the Consumer is involved in consuming the trace

**Comment by Jeremythong2002** [comment]
@samuelneo thanks! could I just check does it mean that you updated this tracer attribute within each map and flatMap method?

**Comment by samuelneo** [comment]
yep

**Comment by joshuagde** [comment]
> I stored it in a `Function<Consumer<String>, String>` (not my idea, got it from my TA), it's a really smart way to make sure the Consumer is involved in generating the trace

Hello could you explain how this works cus i still dont really get it

**Comment by samuelneo** [comment]
it's basically a Supplier that requires passing in a Consumer (instead of passing in nothing). the String that tracer returns should be the same as the String that your lazy supplier returns, so you have to replicate the map/flatMap logic in the updating of the tracer.

the addition is that with the Consumer, you now have a side-effect of the Consumer consuming the String (not the exact String, rather the String concatenated with "traced [step]: ") whenever you update the tracer.

**Comment by MaverickWongKeJun** [comment]
Thanks everyone for the help!
