### ISSUE TITLE
Mock PA 2 Level 2

### ISSUE THREAD

**Issue by ErinaTjin** [nus-cs2030/2324-s2#609]
I'm not sure how to do level 2 and how to continue from here, or how to write the correct predicate for the iterate part. Any help is greatly appreciated T_T

![image](https://github.com/nus-cs2030/2324-s2/assets/157509370/af9d9452-aadd-454d-bf96-5eb3cb170bf1)

**Comment by xiang-qiuyu** [comment]
hello i think you are almost there! for me, i used two stream, one stream that terminates with a count to give the number of times needed to .succ() for the second stream (basically the produce the number of the naturalNum since we cant just Num.of(naturalNum)). the second stream would be to do the iteration on this and then keep .succ() and limit it to the num that u produced from the first stream and then reduce to get the last element out.

**Comment by ErinaTjin** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/157509370/75329d3d-be31-4c65-853a-7494081f58ac)
![image](https://github.com/nus-cs2030/2324-s2/assets/157509370/4a7e49ec-517c-43d8-998f-af391ed0c201)
I tried this, but I am encountering these errors...

**Comment by kaiju10** [comment]
helloo, i will prefer that you revert back to your first stream, as you are really close. The only subtle change you need to make is in the `reduce()` method. To get to know what is going on, this is the `reduce()` method you are using:

`T reduce(T identity, BinaryOperator<T> accumulator)`

`T result = identity;`
`for (T element : this stream)`
`    result = accumulator.apply(result, element);`
`return result;`

In the above code, `result` will be your `n` and `element` will be your `y`.

How does it link with your `iterate()` is this:
1) it will create a stream of elements from `Num.zero()` to `naturalNum` [ e.g. Num.zero(), Num(1), Num(2), ... ]
2) when using `reduce()`, it will iterate through each element, starting from `Num.zero()`
Note that for this single stream case, the value of each element will be useless, as it is just used for iteration for `reduce()`. You will see why later

3) since your code is `reduce(this, (n,y) -> y)`, the iteration will be as follows:
- 1st iteration:  `result` = `this.Num` [ inputted into `y` ], 1st element = `Num.zero()` [ inputted into `n` ], `result` (from formula) = `this.Num`
- 2nd iteration: `result` = `this.Num` [ inputted into `y` ], 2nd element = Num(1) [ inputted into `n` ], `result` (from formula) = `this.Num`
...

because your formula is `y` only, it will keep returning the result as this.Num after applying your formula, which is why your end result might still be the same as your initial input. What you need to do for your formula is to remove `y` and include `n`, and manipulate it such that it **increments by 1** for each iteration. I hope this will help you in understanding why you are creating this stream in the first place
