### ISSUE TITLE
Ungraded EX2 Level 4: How to maintain the Lazy Evaluation?

### ISSUE THREAD

**Issue by mikio13** [nus-cs2030/2324-s2#613]
Below is my current output, I can get the correct order for the trace but I can't make it evaluate only once.

```
jshell> Str.of(() -> { System.out.println("beep..."); return "$0 ==> ";}).join(new Point(1.0, 1.0).toStr())
$8 ==> Str@cc34f4d

jshell> Str.of(() -> { System.out.println("beep..."); return "$0 ==> ";}).join(new Point(1.0, 1.0).toStr()).trace()
beep...
beep...
beep...
traced Str: $0 ==> 
traced Str: (1.0, 1.0)
traced map: $0 ==> (1.0, 1.0)
traced flatMap: $0 ==> (1.0, 1.0)
beep...
$0 ==> (1.0, 1.0)
```

```
public Str map(Function<String, String> mapper) {
        Supplier<String> updatedString = () -> mapper.apply(this.string.get());
        return new Str(updatedString, () -> this.trace.get() + "\ntraced map: " + updatedString.get());
    }

    public Str flatMap(Function<Supplier<String>, Str> mapper) {
        Supplier<Str> updatedStr = () -> mapper.apply(this.string);
        return new Str(
                updatedStr.get().string,
                () -> {
                    return this.trace.get() + "\n" + updatedStr.get().trace.get() + "\ntraced flatMap: " + updatedStr.get().string.get();
                });
    }
```

**Comment by iceflakes12** [comment]
For levels 1 to 3, you had a supplier to lazily evaluate print. For level 4, since print does not inject additional trace print statements, so you need a different pathway for trace to follow, which you have above. So with that alternate pathway you have, just inject relevant print statements and it should work already.

The key thing is making sure that you always go forwards, but making it lazy in a supplier.

**Comment by iceflakes12** [comment]
pretty sure why you have multiple beeps in this case is because of you calling updatedString.get(), try to think of trace as a copy of what you have in level 3, and is completely independent from level 3, rather than using what you have in level 3.

**Comment by mikio13** [comment]
What do you mean by inject relevant print statements? Right now my trace method is this: 
```
    public void trace() {
        System.out.println(trace.get());
        print();
    }
```

**Comment by iceflakes12** [comment]
Ok so basically your trace right now is a supplier that gives one whole chunk of string right?

I am saying let your trace be the supplier that gives only the output string.
But then this differs from the previous level 3 in the case that you also inject many print statements in between.

Basically you do something like this for your flatmap.
return new Str( () -> mapper.apply(this.string).get().string, 
     () -> {
         String x = mapper.apply(this.trace.get()).get().string;
         System.out.println("traced flatMap: " + x);
         return x;
     }
}

and your map should also be doing roughly the same thing. 

and in trace you shouldn't need to call print() already.

So why you have many beeps previously is because you encased updatedStr as a supplier and used it multiple times in your trace, so you end up using mapper.apply(...) multiple times, which ends up causing the multiple beeps. Also your final beep was because you decided to use the print method in trace, which you shouldnt need if you do the above way.

**Comment by iceflakes12** [comment]
By the way the above code will not work for level 5, but the change from level 4 to level 5 should be relatively simple anyway

**Comment by mikio13** [comment]
Thanks alot for the help, i've managed to figure it out :)
