### ISSUE TITLE
Project Test Case 9_11

### ISSUE THREAD

**Issue by ameliaw286** [nus-cs2030/2324-s2#614]
Hi, I have been having some trouble passing this test case for a while :( I have looked through some similar issues here but am still unable to know what I did wrong... Can anyone help point me in the right direction? Thank you!

![Screenshot 2024-04-18 003941](https://github.com/nus-cs2030/2324-s2/assets/153805393/a26d15fc-4dd5-4e92-b099-4389e30c7324)

**Comment by iceflakes12** [comment]
self-check 4 not referencing back to the queue in self-check 3. If there are any people in the queue for self-check 3, they must be served by self-check 4 if self-check 4 is done. 

So how you want to change your implementation is that when self-check 4 is done serving, in the done method, it should search the queue in self-check 3, and if there are people in that queue, then pop one guy off the queue to serve.

**Comment by kryst-ll** [comment]
you can check that when a wait event is processed but no scc is available, your continued wait (or equivalent) has the event time set to the earliest avail time amongst all the sccs. this ensures that when the continued wait event is put into the PQ, it'll be processed before the arrive events of any subsequent customers (ie. 13's continued wait will be processed before 15's arrival, so 13 is served instead of 15)

**Comment by ameliaw286** [comment]
ok thank u everyone! i managed to fix the bug in my wait event!
