### ISSUE TITLE
ug exercise 2 level 2

### ISSUE THREAD

**Issue by m5x4** [nus-cs2030/2324-s2#615]
# Summary
not sure how to implement the flatmap. my map method works fine. do i have to use the supplier interface, i see a lot of people using that? thanks in advance!

## Screenshots (if any): 
Insert Images here if necessary
![image](https://github.com/nus-cs2030/2324-s2/assets/163496829/574e1d96-5f9c-4edd-9bd0-2f0cec7abd28)

**Comment by naomiiiwu** [comment]
hi I think its better not to use optional in this exercise as most getters/methods for optional are banned
I think a supplier is necessary for the purpose of lazy evaluation.. at least I did that HAHA

**Comment by huangtian666** [comment]
hii i think ur `flatMap` should map a `String` to`Str`

**Comment by harvestingmoon** [comment]
In this exercise, its better to switch to a supplier context rather than use Optional since we can't use the Optional methods.

**Comment by W-WJ-Ryan** [comment]
Yep agree with the point on optional, in my opinion not much point using since the getters are banned and then it becomes another context wrapper which you can't access the values inside. I think for map you can just use the function to change the value inside Str and use the constructors to make a new Str. As for flatMap its a bit tricker, but how i did it was to just use the function itself since it already returns a Str object

**Comment by nicklass8** [comment]
hi instead of using the map function of Optional which complicates things alot, since mapper is a function, you can consider using the apply method from the function interface to get your modified string and then wrap it back in a Str

**Comment by m5x4** [comment]
ohh ok thanks all!
