### ISSUE TITLE
Mock PA2 level 1 succ()

### ISSUE THREAD

**Issue by tarshalim** [nus-cs2030/2324-s2#616]
# Summary
Put a summary of the problem here
im super lost how to implement the succ()
## Description 
Describe the problem and any details if neceesary

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
Insert Images here if necessary
my code for succ():
![image](https://github.com/nus-cs2030/2324-s2/assets/163754337/19d7fede-e3a0-4712-b62f-d81607e80fcf)
errors:
![image](https://github.com/nus-cs2030/2324-s2/assets/163754337/22c16796-9161-4c1c-ae93-c75a82026d06)

**Comment by nus2030** [comment]
s is already a function, you can directly .map(s).
valid is also already a predicate, you can directly .filter(valid)

In any case you have to make sure that Num takes in an Optional, a private constructor. else you can just wrap the optional into an abstractnum and wrap the abstractnum in a num.

hope it helps!

**Comment by marvinchoo-mh** [comment]
I feel that is is better to break it down sequentially first you need to check if the number is Valid first using the .filter(valid) followed by mapping it to S using .map(s) to increase it by 1.

For my own implementation when I used the .of method i already check if its valid before hand and if its not valid i will call  a constructor that takes in an Optional.empty()  hence in my succ() method i did not need to check again if its valid again since it will already be an optional.empty().map(s) which returns an empty optional. I hope this helps :)

**Comment by tarshalim** [comment]
thank you for the suggestions, instead of using .filter(valid) can i use AbstractNum's protected isValid()?  ive changed it to this, but im not sure how to create an AbstractNum since this.value cannot be accessed
![image](https://github.com/nus-cs2030/2324-s2/assets/163754337/af48d629-ce1d-4d4f-871d-544d956d7e2a)

**Comment by nus2030** [comment]
dont think this can work, from CodeCrunch is says that "**There is a single instance property opt of type Optional<T>. This is the only property that you need. As such, you are not allowed to define any other instance properties, including constants, in your implementation.**"

this.value should not even exist, rather you should just call super.opt because it is the property that is protected, defined in abstractnum. Im also assuming that your static `of` has already taken care of the validity, so you can make use of it.

1. take the super optional, and map it with s.
2. return the optional from step 1, wrap it in an abstractnum
3. wrap the abstractnum from 2 into a num constructor and return it.

above steps worked for me, hope it helps ur case

**Comment by tarshalim** [comment]
ahh i see, i fixed it now! thanks
