### ISSUE TITLE
How do I make this lazy?

### ISSUE THREAD

**Issue by mfchloe** [nus-cs2030/2324-s2#620]
`Str flatMap (Function String, Str> flatMapper) {
Str res = flatMapper.apply(supplier.get ()) ;
String s = res.supplier.get ();
return Str.of (s);
}`

`static Str of (String string) {
return new Str(() = string);
}`

why is this not lazy even though my factory method returns a Str with a supplier inside?

**Comment by naomiiiwu** [comment]
I think possibly because you called res.supplier.get() which is evaluated eagerly. should wrap it in a supplier then pass into the constructor

**Comment by myathetchai** [comment]
i think it's because in this line: 
Str res  = flatMapper.apply(supplier.get ());

you're already calling the supplier.get() so it'll be eagerly evaluated. this is something my ta shared, hope it helps! :)

// Case 1: Not lazily evaluated
String stuff = fun.apply(log);
return () -> stuff;

// In this case to get the result stuff for use in the supplier, you need to eagerly use the function to apply on the string first

// Case 2: Lazily evaluated
return () -> fun.apply(log);

// In this case since everything is in the supplier, they'll only be called and evaluated when the get() gets called, achieving lazy evaluation

**Comment by prppy** [comment]
bro this is top level knowledge
