### ISSUE TITLE
how to do caching

### ISSUE THREAD

**Issue by prppy** [nus-cs2030/2324-s2#625]
how does caching work can anyone simplify it for me?? 

pwetty please 👉👈

**Comment by myathetchai** [comment]
<img width="576" alt="Screenshot 2024-04-18 at 6 09 58 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156903115/639ac10a-9566-4ff7-9a39-bcb52c11af8b">

i'll try to code trace the example of Lazy's get() method! 
So first Lazy's this.cache is an Optional<T>, and it's not declared to be private so u can modify it later! so if there's already a t in your cache, the t will just be returned. 
But if this.cache is still empty, the supplier under the orElseGet will be called instead, and that's where the supplier under the Lazy class gets first invoked! this t will be returned, and u update ur cache by wrapping the t with the Optional<T> . 
So next time when u call Lazy's get(), ur cache is no longer an empty Optional and they'll just return the value inside it :)))

**Comment by mfchloe** [comment]
I think essentially the idea of caching using Lazy is to defer the computation/getting of value until it's actually needed, thereby improving performance by avoiding unnecessary costs. This approach is particularly useful when dealing with expensive or time-consuming operations that may not be required immediately.

In the lecture notes (lecture 7 slide 11 onwards), 
When the value is first accessed, the lazy initialization mechanism checks whether the value has already been initialized.
If the value has not been initialized yet, the initialization process is triggered.

Once the value is initialized, it is cached so that subsequent accesses do not require re-initialization.
The cached value is then returned to the caller whenever the resource is requested again.

**Comment by lim-4158** [comment]
u should look through the code for the recitation on lazy, it is pretty helpful. Then you could ask more specific questions here regarding parts of the code that you dont understand.

**Comment by prppy** [comment]
thank you and you're welcome for the free class participation.
