### ISSUE TITLE
PA2 level5 Depth incorrect

### ISSUE THREAD

**Issue by ArkAzrael** [nus-cs2030/2324-s2#638]
My current method gets the right number of calls but is missing one depth

This is how it looks like at the moment
![Currentack](https://github.com/nus-cs2030/2324-s2/assets/157274977/b12603b4-6717-4cd1-b224-4211c11d2b22)

I call either the incrementCount() method or the incrementCountAndDepth() method if we are going further down into recursion. I'm not sure why there's a missing depth when the number of function calls are correct.

**Comment by samuelneo** [comment]
I had the same thought process, ended up rewriting the way I'm counting depth. You need to increment depth before a recursive call and decrement it after a recursive call

For what it's worth, the off-by-one here occurs because your base case may possible increase the max depth too, but accounting for that isn't enough, as you'll later see with `ack(4, 0)`

**Comment by ArkAzrael** [comment]
Thank you boss, I managed to get it out somehow with some help

**Comment by UserNameWasTakenAlreadyy** [comment]
@ArkAzrael did u have to completely overhaul this way because i think can still modify the if and else blocks the increment then decrement right? Im also having trouble w this... :(
