### ISSUE TITLE
Exercise 6 Level 2

### ISSUE THREAD

**Issue by cyting01** [nus-cs2030/2324-s2#659]
Hi everyone, my code compiles in the terminal but when I try to submit it to codecrunch , I get "Use of multiple joins detected".

I only have 2 .joins() in the whole file, 1 in my definition of findBusServicesBetween in BusSg, and another one in my describeService in BusRoutes to check whether the list is empty. Are we only limited to 1 .join() in all our classes? I'm not sure how to obtain the values wrapped inside the CF then.

![image](https://github.com/nus-cs2030/2324-s2/assets/153883538/de11dc56-0a21-41a8-8dfa-e73be02ea08d)
![image](https://github.com/nus-cs2030/2324-s2/assets/153883538/5d98d6e8-c3c3-4900-aef4-be7ebe8f13ca)

**Comment by ZHD1987E** [comment]
OK, I just need to let you know that this is actually passing whatever is contained the CompletableFuture around, you only call `join()` on the final state where the Main class is.

**Comment by ZHD1987E** [comment]
So in summary:

You can only have one join. You only need to call this join at the main method.

**Comment by brianpang02** [comment]
level 1 and 2 can be done without any joins. it just involves the passing around of completableFutures

**Comment by cyting01** [comment]
Ah i see, that makes sense. However, how would I obtain the value as a Map<BusService,CompletableFuture<List<BusStop>>> without using .join() then? Since when i use .thenApplyAsync() it will wrap it in the CF.
Similarly, how would I check if the list is empty in describeService if I pass in a CF<List<BusStop>> and I can't use .join()

**Comment by brianpang02** [comment]
> Ah i see, that makes sense. However, how would I obtain the value as a Map<BusService,CompletableFuture<List>> without using .join() then? Since when i use .thenApplyAsync() it will wrap it in the CF. Similarly, how would I check if the list is empty in describeService if I pass in a CF<List> and I can't use .join()

u can mostly copy the codes from the synchronous version. 

for the first question, i assume your are referring to findBusServicesBetween of BusSg class. since it builds from getBusServices(), and getBusServices() returns a cf, you can just start chaining from there e.g. return getBusServices(Stop).thenApply(....)

for the second question again, try to use as much code from the synchronous version. dont forget that your thenApply is equivalent to a map. this means we can have more complex logic within in e.g. thenApply(x -> { if ... else...})

**Comment by TongZhengHong** [comment]
Recall the lecture that you can use `thenApply` similar to a map function. The general idea for `CompletableFuture` is that the supplier function that you pass into `thenApply` basically assumes that the data is received by the CF and you are telling the compiler what to do with the received data. 

You can find an explanation of a conversion of `findBusServicesBetween` and how to deal with the result of `getBusService` [here](https://github.com/nus-cs2030/2324-s2/issues/669#issuecomment-2068139739).

Similar to what @brianpang02 said, most of the synchronous code can be used because in the `thenApply` method, the input to the supplier is assumed to be the result of the CF so you can perform the original computations within the supplier. It is just that this computation is done at a later time in future when the CF completes (i.e. we receive a response from the HTTP server)

**Comment by cyting01** [comment]
Thank you all! Have managed to solve the issue.
