### ISSUE TITLE
PA2 Level 5

### ISSUE THREAD

**Issue by xinnyyy** [nus-cs2030/2324-s2#661]
Hello, does anyone how to approach level 5? Im using flatMaps and put in my solution and defined a FuncStat class with methods such as increment count and getMaxDepth() to store the values but I keep having a compilation error of incompatible types

<img width="584" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/149747847/39c36b90-8df2-4718-9927-1e33319610d1">
<img width="900" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/149747847/a0e2b5df-fa4a-4a55-99ab-f5ba2b20965c">

**Comment by TongZhengHong** [comment]
I think the incompatible types error is from the base case `m == 0` when you update the `FuncStat` state with `n + 1`. The `ack` method expects a `StateM<Integer, FuncStat>` object, but the base case returns a `StateM.<Integer, Integer>` object even after you flatMap it with `unit(n + 1)`. You should **put** a `FuncStat` object instead of an integer to store the state.

There are a few pointers to note as well: 

1. I don't think `stat` is getting updated when you pass it to `put`. Since `FuncStat` is an immutable object, you should be reassigning variable `stat` like this: `stat = stat.incrementCount()` or `stat = stat.updateMaxDepth(...)` or directly passing them to the put method like `put(stat.incrementCount())`. 

2. You should not be calling `StateM.unit(new FuncStat())` since you will be creating a new instance of `FuncStat`, basically resetting the count and maxDepth values every time `ack` is called. 

Instead, we need to retrieve the current state value, so you need to call `get` which replaces the T value with the state value s. From there, you can access the state value s using the `put` method via the lambda function's input variable, which replaces the T value with `Nothing` and updates the state value s accordingly. So what this means is that you should be doing something like this:
```java
// Updating S value:
StateM.<FuncStat>get().flatMap(currentState -> StateM.<FuncStat>put(<<Update currentState  value here>>))

// Updating S value then updating the T value:
StateM.<FuncStat>get().flatMap(currentState -> StateM.<FuncStat>put(<<Update currentState value here>>))
    .flatMap(nothing -> StateM.<Integer, FuncStat>unit(<<NEW integer/T value>>)
```

3. Consider this approach for keeping track of maxDepth instead: 
Since this entire PA involves keeping track of global variables, you should have a `depth` variable that tracks the **current** depth of a function call. As a result, as prof mentioned in #639:
> To calculate depth of recursion, you need to increase depth on method entry and decrease depth on method exit. This would then help you keep track of the call stack's depth.

However, this `depth` variable only tracks the current recursive function call's current depth. Hence, you need to track the maxDepth as well in `FuncStat` which updates when the current depth is greater than the maxDepth. 

You can consider looking at #649, but you will have to add a simple fix as mentioned by @samuelneo to get everything to work.

**Comment by xinnyyy** [comment]
@TongZhengHong hello, thanks for replying! that helped me alot but im still facing an error of my count not being updated properly :(

it returns
jshell> Pair<Integer, FuncStat> result = ack(1, 2).accept(new FuncStat())
   ...> 
result ==> (4, [count=1 maxDepth=4])

<img width="708" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/149747847/c09bcb00-0a08-44e8-88d9-d7bc0457b02f">
<img width="658" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/149747847/d44be208-6b77-4c3c-9d5d-e74ebb057638">

**Comment by TongZhengHong** [comment]
There are 2 glaring issues before addressing your question:
1. In the `m == 0` block, you need to return `n + 1` in the `unit` method instead of `n  + 2`. (follow the given `ack` method)
2. In the else block, to implement the recursive part, you need to call the inner `ack` method first then do the outer one.
    - This is because the inner one gets called first and the returned result is used as input to the outer method call.
    - So something like: `ack(m, n-1).flatMap(inner -> ack(m-1, inner))...`

For dealing with count, the idea is that you want to increment at the start of the `ack` method. However, with the `StateM` implementation, you need to add the result of incrementing to each method call via a flatMap method so you should be calling/putting `incrementCount` before every method call. 
```java
// Normally, without monad/StateM
int count = 0;
int ack(int m, int n) {
    count++;
    ...
}

// With monad/StateM
StateM<Integer, FuncStat> ack(int m, int n) {
    if (m == 0) {
        incrementCount.flatMap(c -> unit...)
    }
    if (n == 0) {
        incrementCount.flatMap(c -> ack(m - 1, 1))
    }
    return incrementCount.flatMap(c -> ack(m, n - 1).flatMap(...))
}
```

As for dealing with max depth, I'm not sure if your implementation is correct, because I don't think the current depth is given by the result of the previous `ack` function call. I would recommend looking at #649, as the given code in the question is very close to the solution but you will have to add a simple fix as mentioned by @samuelneo to get everything to work.

Also, just a side note, please copy your code into Java code blocks (just google how it's done) instead of an image so that it is easier to reference/test it.
