### ISSUE TITLE
PA Level 5

### ISSUE THREAD

**Issue by BZAStudent** [nus-cs2030/2324-s2#667]
![image](https://github.com/nus-cs2030/2324-s2/assets/156635387/7cda13ad-0e32-4beb-97d8-cd48e8d133b0)

Above is my implementation Level5.jsh but i fails the private test case. 
![image](https://github.com/nus-cs2030/2324-s2/assets/156635387/106ec599-16dd-4454-91e8-52bc3570e904)

Seems like I am updating my dept too many time but how can i further decrease the dept count?

Appreciate any help given

**Comment by chinwn** [comment]
At Level 4, you should have:
  inc() {
     get().flatMap(x::Integer -> put(x+1))
  }

 For Level 5, you could try to design two other similar methods
  // used at method's entry
  incrementCntDepth() {
     get().flatMap(stat::FuncStat -> put(..))
  }
  // used at each of the method's exits
  decrementDepth() {
     get().flatMap(stat -> put(...))
  }

**Comment by TongZhengHong** [comment]
It looks like you might be prematurely decrementing depth. The `newStat` object increments depth by one, but you immediately update `newStat` again before calling the next `ack` method. Based on your implementation, assuming that `increment()` only increments count:
- In the `m == 0`, you are not changing depth
- In the `n == 0`, you are only incrementing depth **once**
- In else, you are also incrementing depth once

As prof mentioned, you want to increment on function entry and then decrement when it exits. So you need to increment first before calling the `ack` method, then apply a decrement **after**. 

So it would be something like: `incrementDepth.flatMap(ack(m-1,1)).decrementDepth`. You will have to figure out the exact implementation or you can take some inspiration from:
* #649
You will need to add a simple fix to the above issue to solve this level.

**Comment by chinwn** [comment]
Just to add to Zheng Hong's elaboration

get and put are just primitive methods of the StateM monad, and you can devise larger state-change methods
using them, such as inc(), or incrementCntDepth(), or decrementDepth usually implemented as:
`    get().flatMap(\ s -> put(..s..))`
where ..s.. denotes the changed state.
 
Once you have designed them, you can more concisely use them in your code in ack, roughly as follows:

```
ack(int m, int n) {
   return incrementCntDepth().flatMap(n1 -> {
     if (m==0) {
	     ...
     } else if (n==0) {
         return ack(m-1,1).flatMap(r -> decrementDepth().flatMap(n2 -> unit(r)))
     } else {
         ...
    }});
 }
```

Note that n1,n2 are just nothing and decrementDepth is performed after the ack(m-1,1) call. The order in which these these state-change effects are performed is important which is why monad is used.
