### ISSUE TITLE
Exercise 6 findBusServicesBetween

### ISSUE THREAD

**Issue by ethanmanzz** [nus-cs2030/2324-s2#669]
Inside BusSg class, the findBusServicesBetween method is supposed to have an implementation where it puts in a Map<BusService,CompletableFuture<List<BusStop>>> as the services attribute for the BusRoutes right? 

However, as the getBusServices method returns a CompletableFuture<List<BusService>> already, how do you convert it into a Map<BusService,CompletableFuture<List<BusStop>>> without using the join() or get() method to remove the wrapping of the CompletableFuture. Or should the implementation be for the services attribute for the BusRoutes be CompletableFuture<Map<BusService,CompletableFuture<List<BusStop>>>>, so I wrap it in another CF?

**Comment by TongZhengHong** [comment]
Recall the lecture that you can use `thenApply` similar to a map function. This gives you access to the `List<BusService>` object within the `CompletableFuture<List<BusService>>` object returned from the `getBusServices` method. You can then return any type that you require (in this case you need to return `BusRoutes`)

```java
getBusServices().thenApply(busServiceList -> return something...)
```

The subsequent conversion is similar to the existing implementation since you have access to the list of bus services. You just have to convert `List<BusStop>` to `CompletableFuture<List<BusStop>>`.

No `join` or `get` methods are needed since you can simply combine all your CFs together via `thenApply` or `thenCompose` or `thenCombine` such that you only need to call `join` once in `Main` to retrieve the results.

**Comment by ethanmanzz** [comment]
> Recall the lecture that you can use `thenApply` similar to a map function. This gives you access to the `List<BusService>` object within the `CompletableFuture<List<BusService>>` object returned from the `getBusServices` method. You can then return any type that you require (in this case you need to return `BusRoutes`)
> 
> ```java
> getBusServices().thenApply(busServiceList -> { return something... })
> ```
> 
> The subsequent conversion is similar to the existing implementation since you have access to the list of bus services. You just have to convert `List<BusStop>` to `CompletableFuture<List<BusStop>>`.
> 
> No `join` or `get` methods are needed since you can simply combine all your CFs from other methods together via `thenApply` or `thenCompose` or `thenCombine` such that you only need to call `join` once in `Main` to retrieve the results.

Hi! Thanks for the answer! Ohh so is it  findBusServicesBetween method should be returning a CompletableFuture<BusRoutes> ?

**Comment by TongZhengHong** [comment]
Yes, should be something like this:
```java
public static CompletableFuture<BusRoutes> findBusServicesBetween(BusStop stop, String searchString) { ... }
```
