### ISSUE TITLE
PA2 Time Limit Exceeded

### ISSUE THREAD

**Issue by Jett-Tan** [nus-cs2030/2324-s2#670]
# Summary
Put a summary of the problem here

## Description 
Time Limit Exceeded for ack(4,0)

## Idea s
Describe the approach used (if applicable)

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/68832631/36e92409-533e-4d3a-9b39-a23f24676465)

**Comment by TongZhengHong** [comment]
Could be an infinite loop somewhere in your code, can provide some snippets of it here?

**Comment by Jett-Tan** [comment]
![image](https://github.com/nus-cs2030/2324-s2/assets/68832631/f39fb999-be65-44bd-8962-f1e7b28f4bcb)

**Comment by TongZhengHong** [comment]
I think there are quite a few issues here and perhaps some misunderstandings about the question:
1. Each `StateM` object contains a `T` value (the value you want to store) and a state value `S` (a label, like Log).
2. The `unit` method should take in a `T` value instead of a supplier.
3. The `unit` is meant to create a `StateM` object with the given `T` value ONLY
4. To change the state value, you need to use `get` and `put` methods. 
    - First, we need to retrieve the current state value, so you need to call `get` which replaces the `T` value with the state value `s`. 
    - From there, you can access the state value `s` using the `put` method via the lambda function's input variable, which replaces the `T` value with `Nothing` and updates the state value `s` accordingly. 
5. To combine all these changes together, you use the `flatMap` method.

```java
// Updating S value:
StateM.<FuncStat>get().flatMap(currentState -> StateM.<FuncStat>put(<<Update currentState  value here>>))

// Updating S value then updating the T value:
StateM.<FuncStat>get().flatMap(currentState -> StateM.<FuncStat>put(<<Update currentState value here>>))
    .flatMap(nothing -> StateM.<Integer, FuncStat>unit(<<NEW integer/T value>>)
```
You can consider looking at #649 for inspiration, the code given is very close to the solution but you will have to add a simple fix as mentioned by @samuelneo to get everything to work.
