### ISSUE TITLE
Project Test Case 11

### ISSUE THREAD

**Issue by E0968235** [nus-cs2030/2324-s2#684]
Can't seem to figure out why customer 15 is queueing at SCO 4 instead of 3. 

What I have implemented so far: 
- Wait Event passes to Extra Wait Event where in my Extra Wait Event, I check if server is human or not and if it is SCO, I try to find the earliest avail server and earliest avail timing and use that to create either the service or extra wait event depending  on whether the earliest avail time of server < curr time of event. If human, I just check if earliest avail time of server <= curr time of event and pass it to service event. 
- Service Event checks if server is human or not, if it is SCO, I check if server id == first SCO id and get the updated queue, else if server id != first SCO id, i will remove the customer from first sco and update the serverList to ensure that the first SCO has the updated queue. if human i will remove the customer if it is in the queue and update the serverList for the current server. 

<img width="606" alt="Screenshot 2024-04-22 at 4 18 10 PM" src="https://github.com/nus-cs2030/2324-s2/assets/163379688/b4be5702-38a5-41c0-8e24-2e9552b4508e">

**Comment by tianyiiiiiii** [comment]
hi E0968235m, maybe you can try to check if you have the most updated servers at every point the servers are updated

**Comment by kaiju10** [comment]
helloo, just giving some opinions:
1) For your first pointer, the logic seems okay, but a slight change will be earliest avail time of server <= curr time of event instead of <. There can be a case where the counter is available right on the dot of the current time of event, so this might be a potential issue

2) For your second pointer, I will need more info. I dont get why serverID == first SCO ID, what is the updated queue, and where are you getting it from, unless I have more info on how you create the queue for your counters. I also do see that you are only removing customers if serverID != first SCO ID, but I dont see this will address customers that are assigned to the first SCO ID. I believe I can better help you if you can try to give more details on how your Service Event works
