### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by oneday578** [nus-cs2030/2324-s2#689]
If I don't complete the project, can I still pass the module? Thanks :).

**Comment by W-WJ-Ryan** [comment]
Dun give up bro... still can one

**Comment by ezclap02** [comment]
jiayous bro.. still have a few more days. consider asking your TA, they should want to help you!

**Comment by yeeejieee** [comment]
just post here and wait for help bro

**Comment by ArkAzrael** [comment]
Finals would probably be the bigger deciding factor since that's worth 40% but usually 60-70% of people submit the project according to my TA so not completing it will put you quite far behind the curve. That said if your goal is to pass you usually just have to be in 95th percentile(Don't end up in the bottom 5%) for most modules, not sure about CS though since they do not bell curve.

**Comment by meowmeowpeepee** [comment]
15% a lot sia bro, try ur best

**Comment by HaoZeHuin** [comment]
Jiayou my dude dont give up !

**Comment by oneday578** [comment]
I think I'm just going to give up haha. Thank you all for the advice/encouragement :)
