### ISSUE TITLE
No Getters + Private Final

### ISSUE THREAD

**Issue by limbenben** [nus-cs2030/2324-s2#69]
Hello! In lecture, I believe Prof said we cannot use getter methods because they would violate the OOP principle of Tell, don't Ask - but my TA has been telling me that their use is permissible. So I have been stuck on my lab assignment for a few days because I'm not sure who I should follow - and whether I will be penalised for doing so. Hence I would like to seek clarification on this because there's no point in me using getter methods if I'm going to be penalised, and if I could use getter methods, I probably would have solved the lab assignment sooner haha

P.S. is there any penalty if we cannot score A by our lab submission by 2359 today?

**Comment by joshuagde** [comment]
Hello! From what I have heard you can use getter methods but just discouraged from doing so unless there is no other way to get the information you need. Hope this helps!

**Comment by limbenben** [comment]
Yup! i think my TA said that but i think im more worried about whether we will be penalised / ramifications for doing so in later labs... i think im just very lost because I want to submit a good piece of code but if i do something e.g., make a copy of ImList for local referencing that's also kind of defeating the purpose of the private final initialisation :(

**Comment by LimZiXiong** [comment]
The tell don't ask principle is quite a subtle one. During recitation Prof henry did mention that in some situation using getters is necessary. Take the Pair class as an example that was covered during recitation. If the Pair class does not provide anyway to retrieve the first or second value, what will be the use of Pair? To understand when getters is necessary, take for example Circle and area - if someone were to ask for radius and calculate the area by themselves, it violates tell don't ask since it's perfect possible that circle calculate the area afterall, circle can calculate area itself.

**Comment by hwkchia** [comment]
Issue expired.
