### ISSUE TITLE
Finals Questions

### ISSUE THREAD

**Issue by ethanmanzz** [nus-cs2030/2324-s2#706]
Hi guys

Since the finals is on examplify which has no auto indentation, do we need to code on vim/vscode then paste it in the examplify?
Or can we just code directly in examplify without the indentation?

**Comment by juelin708** [comment]
if i don't remember wrongly we should just type in examplify directly. So maybe can manually indent or just do without indentation, i think it would not matter much

**Comment by CSnoobCS** [comment]
Yeah i remember prof saying similar stuff like as long as you somewhat show some form of indentation will do.

**Comment by JovanFoo** [comment]
Take note it is open book as well, so only hard copy notes!

**Comment by ZHD1987E** [comment]
I tried the final assessment:

- Examplify LOCKS down your computer completely, which means you cannot access anything else!
- Identation totally sucks because you WILL have to indent manually. Trust me, I have done it before. This is not some fancy code editor (VSCode running on Plain Text mode). If need be, let @hwkchia know about this or send some feedback to Examsoft.

To be frank, Examplify is designed for you to type essays, NOT code.

**Comment by ZHD1987E** [comment]
See #720.

**Comment by quadryan** [comment]
You could try using [tab] instead of spamming [spacebar]...

**Comment by ezclap02** [comment]
you can try practicing typing your answers in notepad!
