### ISSUE TITLE
PA2 constructor is ambiguous

### ISSUE THREAD

**Issue by tannorine** [nus-cs2030/2324-s2#743]
Not sure how to resolve this error of ambiguous constructors as I only have one constructor for StateM that takes in Function?

The constructor StateM<S,S>(Function<S,Pair<S,S>>) is ambiguous
The constructor StateM<R,S>(Function<S,Pair<R,S>>) is ambiguous

**Comment by anqixxxx** [comment]
hii i got this error at first too! not sure why but when i removed the types in my return statement it worked
eg. return new StateM<S, S>(....) -> return new StateM<>(....)
not sure if this is what's causing ur issue but hope it helps!

**Comment by gnimnix** [comment]
This is because you have 2 constructors with the same signature. You have 2 constructors that take in a `Function` with arbitrary types and in the eyes of the compiler, they take in the same things. Hence, the compiler does not know which constructor to use (hence the "ambiguity").

Solution is to remove one of the constructors. I suggest keeping constructor `StateM<R,S>(Function<S,Pair<R,S>>)`.
