### ISSUE TITLE
Test Case 9_03

### ISSUE THREAD

**Issue by nicolenahh** [nus-cs2030/2324-s2#744]
# Summary
My implementation:
Wait / KeepWaiting schedules the next event to be a Serve Event for that customer if the customer is first in line. The time for that serve event is the server's next available time at the point of the Wait / KeepWaiting event. However, my Done Event changes the server's next available time to include the rest time and updates it in the server list, but the serve event has already been scheduled at the "old available time". Hence my server doesn't rest. How can I improve my Wait / KeepWaiting logic?

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
<img width="432" alt="Screenshot 2024-04-25 at 11 56 21 AM" src="https://github.com/nus-cs2030/2324-s2/assets/89764765/51c9b6f4-765b-4c53-84e0-3ef03fd214a8">

**Comment by kongshiting** [comment]
hi! for me I had the same issue and to solve this i considered another condition before returning a serve. for serve to be returned, the available time has to be equal or lesser than the time, such that you account for the fact that the available time might be updated again. essentially, you return another KeepWaiting event before your serve. for me, I found this quite confusing so you can think about this additional KeepWaiting as a "PreServe" event, but essentially it works the same as KeepWaiting and you can implement this logic there!

**Comment by hanlinnnnn** [comment]
similar to what was shared by shiting, my wait event would return a blindlywait(keepwaiting or whatsoever) event at the same humanserver at its next available time, which will return a serve event at that same time when processed, serving as a preserve event. if it was a blindlywait at a selfcheckoutcounter, and the counter is available, it would return a serve at that counter rightaway, otherwise it would check for the earliest available selfcheckoutcounter and return a blindlywait at the new counter. if it was blindlywait at a humanserver, and the server is available, it would return a serve at that server rightaway, otherwise it would simply return a new blindlywait at the server its next available time.

**Comment by W-WJ-Ryan** [comment]
Hi, i think what you can do to circumvent this issue is to instead of straightaway creating the serve event, have your intermediate keepWaiting event check first if the server is indeed available at that time before going to serve, that way in the event your server gets updated along the way, it will still be reflected. All the best!

**Comment by nicolenahh** [comment]
Thank you everyone for your input, I got it :)
