### ISSUE TITLE
Project Error 9_01

### ISSUE THREAD

**Issue by Castelle-code** [nus-cs2030/2324-s2#746]
## Description 
I do not know why my customer 6 is not served at the correct timing but the previous customers are served correctly? Been trying to fix but to no avail.

I only called restTime one tine at DoneEvent class. 

## Screenshots (if any): 
<img width="391" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/157040750/491e3e93-fdf2-4a2d-b2c0-3c92620679f9">

**Comment by W-WJ-Ryan** [comment]
Hi are the customers after that served in the correct order and time? If they aren't it could be because you are calling the wrong serviceTime likely due to creating serve customer events in the wrong order.

**Comment by LimJiaWeng** [comment]
I think the issue could be because your code doesn't check your finish time correctly for the customers in queue when the server has to rest. Maybe check whether your event that handles still waiting customers properly updates the finish time to include rest time before calling serve. Adding print statements to your Simulate class can help with this.

**Comment by citronwhitetea** [comment]
does seem like a rest time issue... maybe you can check if you have updated your serversavailabletime correctly after getting the rest time. and ensure that this updated server, and eventually updated serverslist is passed onto the necessary event classes

**Comment by joshualek09** [comment]
its strange as your before and after 6 serves 1 is all correct. as you said you also only call restTime once and in one location. 

this leads me to have the impression that you are not passing in the server's nextService correctly. For example, if you look at the moment 4 serves by 1 until 6 serves at 1, we know that 6 is the second customer to be waiting at 1. So i think that what's happening is that 5 knows 1's next service (4.053) and 6 is getting 5 doneTime (5.053) without considering considering the restTime. Hence, you should check that you are 
1. updating the server correctly and then update the serverList in time, before
2. your Waiting event retrieves the server's doneTime.

**Comment by Tayjunzhi** [comment]
Your server list is updated only after DoneEvent so the servers are resting properly (Customer 3 - 4). You might want to look at your WaitEvent again because it is generating a ServeEvent before DoneEvent (when your servers rest and the list is updated). Maybe you can check if the server is available before your WaitEvent generates a ServeEvent.
