### ISSUE TITLE
2122 Sem 2 Final Q3

### ISSUE THREAD

**Issue by BZAStudent** [nus-cs2030/2324-s2#749]
Hello for question 3, can I change Maybe<T> to Maybe<Optional<T>> such that when mapping, i check whether my this.opt.equals(Optional.empty()) etc...

Or do i need to change it to abstract class Maybe<T> and have 2 different classes inherits from Maybe<T>?

![image](https://github.com/nus-cs2030/2324-s2/assets/156635387/6fbb7f91-6ea2-48cd-8595-a76bdf3763e0)

Thank you

**Comment by ArkAzrael** [comment]
Do you need to inherit 2 classes? You can write static methods in an abstract class.
I think a ConcreteMaybe<Optional<T>> extends Maybe<T> should be enough?
Since you can put an Optional.empty() and a Optional<T> in it, just return new ConcreteMaybe(Optional.empty()) for empty() and new ConcreteMaybe(Optional.of(T)) for of(T)

**Comment by Shazard07** [comment]
> Do you need to inherit 2 classes? You can write static methods in an abstract class. I think a ConcreteMaybe<Optional> extends Maybe should be enough? Since you can put an Optional.empty() and a Optional in it, just return new ConcreteMaybe(Optional.empty()) for empty() and new ConcreteMaybe(Optional.of(T)) for of(T). Then you put all the other methods into ConcreteMaybe so there's no cyclic dependencies in the sense that Maybe only calls ConcreteMaybe for empty and of and everything else like toString and map is handled by ConcreteMaybe

thanks
