### ISSUE TITLE
Project Test Case 9_9

### ISSUE THREAD

**Issue by yminnnx** [nus-cs2030/2324-s2#751]
# Summary
currently stuck at test case 9_9 and not sure how to proceed as my customer is waiting instead of getting served by self-checkout

## Description 
currently this is my arrive code
<img width="703" alt="Screenshot 2024-04-25 at 3 57 21 PM" src="https://github.com/nus-cs2030/2324-s2/assets/163486879/1d5efebc-cd55-440d-9b66-8695f14465b7">

## Screenshots (if any): 
This is the error that I am currently facing
<img width="590" alt="Screenshot 2024-04-25 at 3 53 10 PM" src="https://github.com/nus-cs2030/2324-s2/assets/163486879/e8498281-79cb-4736-92b6-71aac9127b83">

thank you!

**Comment by gnimnix** [comment]
Does `Wait` return a `Serve` event? What if the wait time is 0?

**Comment by Chrisallan29** [comment]
Hi, when i was facing this issue, i decided to use a global queue for my selfcheckouts. I think you can consider using this approach as it greatly helped in my selfcheckout queue logic.

**Comment by andhika2002** [comment]
could you check your condition for arrive -> serve? seems like it skips your arrive -> serve and enters the arrive -> wait clause.

**Comment by joshualek09** [comment]
hi, i was stuck at this test case too. 

i concur with @andhika2002, and to add on,
 
1. you should check your arrive -> serve, 
- in particular, how you determine if there are any free servers. 
- free servers should be those that can serve immediately. 
- hence your checking condition most likely is flawed as it is returning a wait instead of serve. More so as 0.035 is almost the start of the simulation, so iirc, im certain that SCC 2 is not serving anyone 

on that note, 
2. you might want to check your toString() for SCC, 
- for instance, your output shows that it waits at "1". 
- even if it is waiting, since in ur ss below it already shows "self-checkout 1", we can deduce there are no human servers, only SCC. So your output should be seeing waits at "self-checkout 1". (even if the free server logic is wrong) 
- this leads me to have the impression that the way you update your servers is also flawed. do check that when updating your SCC you return an SCC object. 
- for example, in my implementation, SCC is a subclass of Server. I initially made this error that i just mentioned, so even though i THOUGHT i was updating my SCC correctly, but because the event calls the update method from the Server (super) class, so the return type was a Server object, and consequently, that SCC object in the serverList became a Server object. So what i did to solve this was to @ Override the same update method in the SCC (sub) class and make it return an SCC object. This way, in any event where i perform some server function like server.updateServerList(), regardless of the server object being from Server class (super) or SCC class(sub), the return object type is as intended.

hope this helps. cheers.

**Comment by yminnnx** [comment]
thank you all for the advice! i have managed to solve it using @joshualek09 inputs!
