### ISSUE TITLE
Project Test Case 9_04

### ISSUE THREAD

**Issue by kat-font** [nus-cs2030/2324-s2#752]
Why is this happening? When customer 4 is served at the wrong time does that mean there's an issue with server 2's rest time? But I passed test case 9_03 so I thought I fixed my rest time already. Any help appreciated :(

<img width="517" alt="Screenshot 2024-04-25 at 6 08 03 PM" src="https://github.com/nus-cs2030/2324-s2/assets/163483287/6649c1eb-9853-417c-b066-f73e65307777">

**Comment by lohkeyyy** [comment]
Take note of the amount of times you call the restTimes supplier. Call it once each time a server is done serving. Excess calls will affect the rest time given from the supplier.

**Comment by hohinnn** [comment]
^you might be calling it too many times or calling it at the wrong events

**Comment by joshualek09** [comment]
in addition to what @lohkeyyy said, you can also add println statements so that each call will print a message (eg. "calling serviceTime supplier for customer <id>"). thereafter, just count the number of println statements (or have a counter) to make sure it == number of customers served. if it ==, then you know that its not the issue of how many times you call it. 

furthermore, you should only call it only in one location. for instance, if your rest logic is done in the Server class, then ideally your .get() for it should be done there too. Supplier restTime should also be a Server attribute, while Supplier serviceTime is a Customer attribute

**Comment by hanlinnnnn** [comment]
> in addition to what @lohkeyyy said, you can also add println statements so that each call will print a message (eg. "calling serviceTime supplier for customer "). thereafter, just count the number of println statements (or have a counter) to make sure it == number of customers served. if it ==, then you know that its not the issue of how many times you call it.
> 
> furthermore, you should only call it only in one location. for instance, if your rest logic is done in the Server class, then ideally your .get() for it should be done there too. Supplier restTime should also be a Server attribute, while Supplier serviceTime is a Customer attribute

Great tip for debugging! Would save you a lot of time to know where your error is (I didn't know where mine was and spent 3 hours turning the right part of my code wrong ..)

**Comment by bmok02** [comment]
you might also want to check ur simulator as well bc the issue with mine initially was that when my simulator is managing the PQ i kept calling the nextEvent() method twice in order to get the pair.first() and pair.second()

**Comment by kat-font** [comment]
Thanks everyone! I realised I was calling nextEvent() more than necessary because of my logic so I finally fixed it :)
