### ISSUE TITLE
Project test case 9_11

### ISSUE THREAD

**Issue by wxlee1807** [nus-cs2030/2324-s2#759]
# Summary
hi! I have trouble with this test case. I previously tried searching the github for any solutions and implemented the for loop for checking the available servers and updating the earliest timing from the server list, but im not sure why this issue still occurs. anyone knows where im going wrong?

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
<img width="649" alt="Screenshot 2024-04-25 at 9 46 40 PM" src="https://github.com/nus-cs2030/2324-s2/assets/156640028/968b02c4-d254-4a8c-abf6-a3add7fc7a45">

**Comment by lohkeyyy** [comment]
can you show us Arrive event? the issue is clearly there as after 17 arrives, instead of a wait event, a leave event is added

**Comment by quintenksh** [comment]
Ahh I have the exact same output! I will let you know if I figure it out ://

**Comment by vanesssalai** [comment]
you can look at #730

**Comment by tarshalim** [comment]
perhaps your customer queue for self-checkout isnt properly updated?

**Comment by finnerrrrr** [comment]
^ check your implementation for updating of your self checkout server's queue and how your wait event in self check queue -> serve event for the correct self check.

**Comment by kaiju10** [comment]
I can see the issue lies in how self checkout 4 is not taking any customers from the central counter queue, and is only taking in new customers that arrive. Only self checkout 3 is tanking the queue, which is why customer 14 gets served by self checkout 3 instead of self checkout 4. You might want to check out if the customers are updating their event times according to the next **earliest available counter**, instead of relying solely on the **first counter** (in this case is self checkout 3).

**Comment by wxlee1807** [comment]
hi! thanks all for the feedback above~ i have passed the test case! the problem with mine was my done event cos it didnt reflect the return timing of the servers properly!
