### ISSUE TITLE
Printing IntStream

### ISSUE THREAD

**Issue by branbranyu** [nus-cs2030/2324-s2#766]
<img width="440" alt="Screenshot 2024-04-26 at 11 15 33 AM" src="https://github.com/nus-cs2030/2324-s2/assets/164456159/184ac4ba-5178-46c8-ba3a-d0d68baeedc9">

How would you print an IntStream that returns OptionalInt?

**Comment by sarahquan** [comment]
<img width="647" alt="Screenshot 2024-04-26 at 11 23 41 AM" src="https://github.com/nus-cs2030/2324-s2/assets/154739486/0ae16957-b1e2-4592-955e-4a6ae0cecb0e">

First one to see whats going on inside reduce

Second one just to see range? 

Cannot use forEach to see because both forEach and reduce are terminal operations

**Comment by branbranyu** [comment]
thank you!

**Comment by sarahquan** [comment]
ur welcome!
