### ISSUE TITLE
Project last event serves prematurely

### ISSUE THREAD

**Issue by sqngwdn** [nus-cs2030/2324-s2#769]
![Screenshot 2024-04-26 143330](https://github.com/nus-cs2030/2324-s2/assets/164153724/acdfc13a-758f-424c-838d-35a4f169e87f)
![Screenshot 2024-04-26 143744](https://github.com/nus-cs2030/2324-s2/assets/164153724/c2208306-b0f4-4741-9804-d634c1919ce6)
**As seen on the screenshots, my output is pretty much the same except at 10.006, my event 10 is served right after event 9 is served when it should continue waiting.**

This is my simulator: 
![Screenshot 2024-04-26 144544](https://github.com/nus-cs2030/2324-s2/assets/164153724/6121c6fa-b828-4f6f-9fbd-5fd3d8f25ec6)

For context, I do not have a customer class and instead I treat every Event as a customer. I also have a WaitMore event which is the result of doEvent for a Wait event; this is the only event where (lowPriority: true) by default so the loop in my simulator is looping to filter out all the WaitMores, put them in a lowpq until there are none in the main pq, and at the end of the loop add all the WaitMores back, but this time they have lowPriority: false as doing a WaitMore returns the same WaitMore with !this.lowPriority.

This is my WaitMore class:
![Screenshot 2024-04-26 145218](https://github.com/nus-cs2030/2324-s2/assets/164153724/d87dd25e-9974-4829-a8a4-74470c792ec6)

The reason why the doEvent of a WaitMore returns a new WaitMore with !this.lowPriority instead of (lowPriority: false) is because if i add back the WaitMore with lowPriority: false into the loop, it will not be filtered out in the "while (extractedEvent.islowPriority())" loop and be passed on to the loop below, and the doEvent also returns a (lowPriority: false) and permanently polls that event.

E.g. adding back WaitMores with (lowPriority: false) will not be filtered and be passed to the loop below. if the doEvent returns a WaitMore with (lowPriority: false) again, the entire while loop will keep polling this event as it has the lowest arrivalTime (my comparator filters based on time first) which will cause an infinite loop error.

**I have this similar output issue with other test cases, where only the last server is being served right after the second last server is served. Would anyone be able to figure out why?**

**Comment by joshualek09** [comment]
hi sangwon, 
the primary problem would be that you are using 2 pq, which i **think** is highly discouraged. one possible reason would be the added complexity and as far as I know, you are the first to use it. 

next the issue is evidently that your WaitMore event is not getting the server's updated nextServiceTime consistently. So for example, if Server 1 is currently serving C1 and next service time is 1.00, when C2 and C3 come in and wait at server 1 then you do manage to pass in the correct nextServiceTime of 1.00. However, once Server 1 starts serving C2 (ends 2.00), your C3 (WaitMore) is not updated with the timing of 2.00. Thats why ur output will look like at 2.00 both C2 and C3 is served.

furthermore i think you can further abstract out sections your code. when creating the serverList(tempList) you can abstract out into a private function in the simulator instead of keeping it in the simulate(). likewise, when running the simulate you can further abstract out the whole simulation into a private function, so that your simulate() will be like 3 lines ish - ie. 1. create serverList, 2. create PQ, 3. process PQ and thus return output.

also i highly suggest abstracting out your customer into a customer class. while the cust class code is really short, but when doing your events your code will be much more readable in terms of how you handle the customer, such that when you return a new event you dont have to put in like 7 attributes.(which most likely will see a deduction in style points - my speculation)

**Comment by sqngwdn** [comment]
@joshualek09 thanks for your detailed advice. In fact, I am working on the abstraction right now but I just wanted to make sure my logic works before abstracting.

As for the double pq however, in your example C3 would be updated with the new list because everytime I doEvent for a WaitMore, the doEvent(tempList) takes in the most recently updated list and returns a new WaitMore with that list. If this was not the case, the previous inputs would have been wrong as well not just the last server. 

But you do make a good point on the added complexity of the double pq so I will see how I can work around that. Thanks a lot!

**Comment by dingus891** [comment]
hi sangwon i think another thing you can look into is your "god" simulate method where everything is done. For one this is something they have advocated against for since lab 2. while this may not be as useful as @joshualek09 in helping solve your problem. One thing you should do is create private methods to create the PQ Servers etc
