### ISSUE TITLE
Project Test Case 9_11

### ISSUE THREAD

**Issue by weiyangng** [nus-cs2030/2324-s2#772]
# Summary
Any suggestions on how I can fix this?

My program seems to be mixing something up between my human and self checkout servers

## Screenshots (if any): 
![image](https://github.com/nus-cs2030/2324-s2/assets/158589429/29de97be-8493-464c-9d4e-a9271960c743)

**Comment by joshualek09** [comment]
hi weiyang you may wish to refer to my comment below for a similar post #751. for your ease of reference, i have copy pasted my response below, but put simply my very last point could perhaps be the explanation for your issue (mixing up human and scc) - when you update your servers, particularly your SCC, you are returning a Server object instead of an SCC object.

my response below: 
i concur with @andhika2002, and to add on,

1. you should check your arrive -> serve,
- in particular, how you determine if there are any free servers.
- free servers should be those that can serve immediately.
- hence your checking condition most likely is flawed as it is returning a wait instead of serve. More so as 0.035 is almost the start of the simulation, so iirc, im certain that SCC 2 is not serving anyone

on that note,
2. you might want to check your toString() for SCC, & how you update the serverList
- for instance, your output shows that it waits at "1".
- even if it is waiting, since in ur ss below it already shows "self-checkout 1", we can deduce there are no human servers, only SCC. So your output should be seeing waits at "self-checkout 1". (even if the free server logic is wrong)
- this leads me to have the impression that the way you update your servers is also flawed. do check that when updating your SCC you return an SCC object.
- for example, in my implementation, SCC is a subclass of Server. I initially made this error that i just mentioned, so even though i THOUGHT i was updating my SCC correctly, but because the event calls the update method from the Server (super) class, so the return type was a Server object, and consequently, that SCC object in the serverList became a Server object. So what i did to solve this was to @ Override the same update method in the SCC (sub) class and make it return an SCC object. This way, in any event where i perform some server function like server.updateServerList(), regardless of the server object being from Server class (super) or SCC class(sub), the return object type is as intended.

hope this helps. cheers.

**Comment by weiyangng** [comment]
thanks josh but I have finished, appreciate the insightful comment though
