### ISSUE TITLE
Project 9_15

### ISSUE THREAD

**Issue by ErinaTjin** [nus-cs2030/2324-s2#780]
I encountered this error, any ideas on what could be causing it?

![image](https://github.com/nus-cs2030/2324-s2/assets/157509370/0be7b370-e843-4b17-a089-e0d888e95008)

**Comment by cth06-Github** [comment]
I am not very sure how to help without being able to see your code haha but I will share some of the potential pitfalls I had...maybe see if it helps?
As all the self-checkout counters seem to be working, there could be something wrong with the logic handled for human servers or events associated with the human servers.
Customer 22 is supposed to be served by server 2 at 3.406 timing but it did not happen. This may suggest that the event timing of the serve event for customer 22 is wrong. But given that for your code, before even customer 22 is served, customer 27 arrives and is served by server 2, it feels like the transition from wait event to serve event went wrong(?)...like somehow the nextEvent wasn't executed.

When I debugged my code, I realised that there were errors from earlier parts of the project not caught until the future test cases, so this might also be the case for you as well. Oh yes I also would like to mention that passing _fewer_ test cases after rectifying code does not mean that the correction is in the wrong direction, it may mean that it was partially corrected (which was what happened to me).

Here are some things to check for the code for the entire project (I am sorry if there are some inaccuracies below but these were what I ensured):
- [ ] service Timings for servers are only `supplier.get()` in serve event
- [ ] rest Timings for human servers are only `supplier.get()` in done event
- [ ] For the transition of wait event to Serve event for human servers, (I am guessing the logic will go like WaitEvent.next() gives Serve Event)...you might not want to directly create a serve event there and then but later on because...let's give an example: Customer 4 & Customer 5 are queuing at Server 2. Then, Server 2 just started to serve Customer 4. So I am guessing that typically the code will go like okay since server 2 is serving customer 4 now, which means we know when customer 4 will be done serving, we know when customer 5 will be served so we can transit Customer 5 Wait Event into serve event since we can predict when customer 5 is served. But issue here is that right after customer 4 is done being served, the server might go to rest which means that there must be a way to update customer 5 event to delay the serving or just do something about it 
- [ ] I made the mistake of decreasing the queue length whenever a customer is served at the server without checking whether or not the customer came from the queue or came from Arrive Event
- [ ] Depending how one implements the Wait events... (because I have still wait events where if customer need to continue waiting then another wait event will be called) For self-check out counters, if a wait event need to be transited to another wait event, the event timing of the next wait event should be the SMALLEST of all other self-checkout counters end occupied timing. To explain further, let's say we have wait event for customer x at self checkout 1. Self checkout 1 is supposedly to finish serving another customer at 1.33 timing. Self-check out 2 is now full but will be available at 0.56 timing for example. If a next wait event is needed for customer x at self-checkout 1, the event time for the next Wait event for customer x at self-checkout 1 should be 0.56 (or any other "serving done" timings that is the SMALLEST of all other self-checkout counters) and not 1.33
- [ ] Assuming that one updates the queue of any server in serve event, then ensure that if self-checkout counters are associated with the serve event, the queue is updated NOT at the self-checkout counter that is serving the customer. We need to find the self checkout counter that supports the queue and update the queue of that counter.

This is all I can remember. Not sure if I am comprehensible because my implementation may be different from yours but hope this gives some idea!

**Comment by yf-yeoo** [comment]
Just to add on to the above answer, someone created a really useful test case which helped me work out the possible issues and pass test case 15. You can consider using it, it is available at Issue #724

**Comment by ErinaTjin** [comment]
I created a rest event, which updates the rest timings of the server and its next available time
My wait event doesn't return a serve event, because I let the rest event check if there's any customers in the queue and create a serve event for them
Wait event:
![image](https://github.com/nus-cs2030/2324-s2/assets/157509370/6a9d0b47-00f5-4e0d-ad4c-cef5e263db14)

RestEvent
![image](https://github.com/nus-cs2030/2324-s2/assets/157509370/5a292c55-ea25-4ce2-a942-f4e3e254980c)

**Comment by ErinaTjin** [comment]
Thanks everyone! Turns out that the issue is that my rest event's timestamp is at the start of the rest period, not at the end. So if a customer comes and waits in between those timings, the rest event wouldn't be able to detect the customer at the start of the rest period and create a serve event for them
