### ISSUE TITLE
anyone can explain what does declaring something static do as compared to not declaring?

### ISSUE THREAD

**Issue by joashlim22** [nus-cs2030/2324-s2#784]

**Comment by alterVega** [comment]
Declaring a method static allows you to use that method without first instantiating an instance of that class, so you can call the method directly with ```class_name.method_name()```. if you dont declare static, you must first instantiate with ```new class_name()``` and then calling the method on that

**Comment by CSnoobCS** [comment]
the most frequent method we used is the “of”.

**Comment by oneday578** [comment]
Hi, if you look at the code below, of is static while of1 is not. Basically, if you try to call Example.of1(10) without an instantiated Example object before e.g. new Example(5).of1(10) it'll give an error. Hope this helps :).

Code:
![image](https://github.com/nus-cs2030/2324-s2/assets/98032386/89807286-e868-4b5f-8ada-fa376932e2d5)
Instantiated:
![image](https://github.com/nus-cs2030/2324-s2/assets/98032386/be4ba884-b907-457d-8501-161cf0d720b1)
Error:
![image](https://github.com/nus-cs2030/2324-s2/assets/98032386/47db3925-3bdc-4897-a6c2-d950059da2bb)

**Comment by azzy83** [comment]
Means you can use it without creating an instance of the class, like Optional.empty() , empty() is a static method, you dont have create the class first all that

**Comment by hanlinnnnn** [comment]
a static attribute or method belongs to the class, and not any specific instance of the class. static attributes and methods are to be accessed using the name of the class and not through an instance reference.

**Comment by cherylkohzw** [comment]
When declare static, you can access directly by calling CLASS.<method>

**Comment by W-WJ-Ryan** [comment]
> a static attribute or method belongs to the class, and not any specific instance of the class. static attributes and methods are to be accessed using the name of the class and not through an instance reference.

hi just to add on, while static allows you to directly call it from the class without instantiating it, you don't necessarily have to, just that it is not recommended since it often causes quite a bit of confusion

**Comment by jaydenntann77** [comment]
Declaring a member of a class as static means that it belongs to the class itself, rather than to any instance of the class. This distinction impacts how the member can be accessed and how it behaves compared to non-static (instance) members.

Static members can be accessed directly using the class name without needing to instantiate the class. This makes them useful for utility functions or constants.

On the other hand, you need to create an instance of the class to access non-static members.

**Comment by tyy28** [comment]
By declaring static, the method can be used without instantiating the class

**Comment by lifrocszh** [comment]
Static is a keyword to mean "constant", meaning that it is tied to the class instead of the object. 

So static methods are common methods across all classes and can be used without creating the object, so you call 
<class name>.<static method> like Optional.of, but you cannot do Optional.map since it is not a static method. 

Static properties is a common variable shared across the entire class. Using Point as an example, let say i have a public static double z = 1.000, calling Point.z will return 1.000, it is sort of a constant. Therefore if i modify z, the change will be reflected among all Points.

**Comment by luudgia** [comment]
declaring a method as static means the method belongs to the class itself rather than to instances of the class. so you can access a static method using the class name directly, without needing to create an instance of the class vs you need to create an instance of the class and then call the method using that instance.

**Comment by joashlim22** [comment]
ok thank u all!

**Comment by ZHD1987E** [comment]
@joashlim22 Close your issue if you don't mind :)
