### ISSUE TITLE
Mock Paper qs1

### ISSUE THREAD

**Issue by meowmeowpeepee** [nus-cs2030/2324-s2#786]
![image](https://github.com/nus-cs2030/2324-s2/assets/164331190/9c6937b1-dcd6-486a-9f9f-32b57a3fb43d)

Im not sure why this works, because when u do this, wouldnt it still call `this(FilledCircle.radius)`, and radius is not accessible for FilledCircle since it is private.

and just to confirm, in my FilledCircle class, I cannot call super.radius or super.circle cos they are private right, I can only call if they are protected...

**Comment by joshualek09** [comment]
hi, regarding your second question, you are right. 

the child class FilledCircle cannot directly access the private radius field of its parent class Circle using super.radius. Private fields are not accessible outside of the class in which they are declared, not even to subclasses. If you want the radius field to be accessible to subclasses, you could change its access modifier to protected instead of private. This way, subclasses like FilledCircle would be able to access the radius field using super.radius.

But if you want to access the value of the radius of Circle (parent), you can create a public getter method for the radius field, such as getRadius() in parent Circle, then the child class FilledCircle can call super.getRadius() to retrieve the value of the radius from its parent class. Since getRadius() is a public method, it can be accessed by subclasses like FilledCircle, allowing them to obtain the radius value from the parent class.

**Comment by xiang-qiuyu** [comment]
i think for your first question, since the constructor for Circle takes in another Circle and not a FilledCircle, you are not calling FilledCircle.radius but Circle.radius as your FilledCircle is read as a Circle in the Constructor. (i think)

**Comment by kprajogo** [comment]
I don't think you can super.radius and super.circle, maybe can use getters but seems anti-oop

**Comment by meowmeowpeepee** [comment]
understand, thank you guys
