### ISSUE TITLE
Project Test Case 9_11

### ISSUE THREAD

**Issue by urmothergei** [nus-cs2030/2324-s2#787]
# Summary
Hi i have been stuck on this test case for project. anybody faced this before have any ways to solve this?

## Description 
Describe the problem and code snippets if necessary 

## Screenshots (if any): 
Insert Images here if necessary
<img width="440" alt="image" src="https://github.com/nus-cs2030/2324-s2/assets/126307515/f0a6e9a9-79bc-480d-a6e0-afff615b9e29">

**Comment by cth06-Github** [comment]
Looking at the test case output, it seems that the code isn't able to determine whether self-check 3 is being occupied when customer 15 arrives. Because for your output, 3 done serving by self-check 3 (in line 63) is correct, so from line 34 to line 63, self-check 3 shouldn't be serving anyone yet self-check 3 serves customer 15 when customer 15 arrives. Also, for your output, self-check 4 is serving 2 customers (customer 13 & 14) at the same time. So you might want to check the code for that -- the code for server, arrive event etc.! I suspect (though I am not too sure) that when creating the next event for the particular customer, the code created a serve event for that customer when it should not been created so early on. (?)

You may want to look at the comments given in issue #780. Someone shared about potential pitfalls for the project and another mentioned the presence of a really useful test case that can be found in this forum for debugging. Maybe this will help!

**Comment by LimJiaWeng** [comment]
your self-check 4 serves both 13 and 14 at the same time so maybe you could check whether you are correctly updating the finish time of your self-checkouts when a customer is being served so that the same self-checkout does not serve 2 people at the same time. You can try adding print statements for your server finishTimes/ queues and using the test cases provided in #758 to check whether your code works as intended.

**Comment by lohkeyyy** [comment]
had the exact same issue, after tracing my code i realised the issue came from my serve class. you may have implemented yours in a different way but the serve class is a good place to start.

**Comment by hanlinnnnn** [comment]
make sure you are using the most updated server every time u process an event. i would suggest getting it from the list of servers every time rather than using this.server of the event as the list of servers may have been updated by other events.

**Comment by urmothergei** [comment]
okay thanks everyone! just figured out.

**Comment by cherylkohzw** [comment]
You need to check your self check outs. Can only queue and dequeue at the first self check out. Hence in your arrive class you need to check if it queues at SCO, queue at first SCO. Same for wait class and serve class when you dequeue
