### ISSUE TITLE
Concept on currying

### ISSUE THREAD

**Issue by tyy28** [nus-cs2030/2324-s2#797]
As I was going through the lecture notes for revision, I reached the part on currying and I can't seem to comprehend what it means, can someone simplify the concept/provide an example to aid my understanding?

**Comment by LimZiXiong** [comment]
It's basically passing partial function around. For example to add 2 numbers, one can write (x, y) -> x + y. You can also rewrite it as Function<Integer, Function<Integer, Integer> a = x -> y -> x + y. If you do a.apply(5) you still have an incomplete function but it can be passed around

**Comment by jaydenntann77** [comment]
Imagine you have a function that takes two arguments. Currying this function would mean transforming it into a function that takes the first argument and returns another function. This returned function then takes the second argument and finally computes the result.

Currying is useful because it allows you to create specialized functions by fixing some parameters, which can be reused without repeatedly specifying the fixed parameters.

A simple example would be as follows:


```
// Curried function to multiply two numbers
Function<Integer, Function<Integer, Integer>> curriedMultiply = a -> b -> a * b;

// Creating a function that multiplies any number by 2
Function<Integer, Integer> doubleFunction = curriedMultiply.apply(2);

System.out.println(doubleFunction.apply(5)); // Output: 10
System.out.println(doubleFunction.apply(3)); // Output: 6
```

The `curriedMultiply` variable holds a lambda expression that represents a curried function. It takes the first integer a and returns another function. This returned function takes the second integer b and finally performs the multiplication of a and b.

`doubleFunction` is another function created by applying the first argument (2) to `curriedMultiply`. This returns a new function that takes an integer and doubles it.

**Comment by CSnoobCS** [comment]
thanks for the examples, these definitely made the thing easier to understand.

**Comment by kongshiting** [comment]
hi! currying transforms a function that takes multiple arguments into a sequence of functions that each take in a single argument (aka partially apply a function and create a new function with fewer parameters)

the above examples are correct and explain the concept well, but note that this function can take in multiple arguments, so more than two. added another example with three arguments!

// two arguments
Function<Integer, Function<Integer, Integer>> add = x -> y -> x + y;
add.apply(2).apply(3)
// output: 5

// three arguments
Function<Integer, Function<Integer, Function<Integer, Integer>>> addThreeNumbers =
	x -> y -> z -> x + y + z;
add.apply(2).apply(3).apply(4)
// output: 9

hope this helps! all the best for finals :-)

**Comment by tyy28** [comment]
ah okay all these examples really helped, thanks guys and all the best for finals!
