### ISSUE TITLE
Pure Functions (Side effect)

### ISSUE THREAD

**Issue by zwz1707** [nus-cs2030/2324-s2#813]
Hi, I understand that pure functions are free from side effects but I am still unsure of the 3 types of side effects? Can anyone give an example of each (especially the program input and output side effect) and explain a bit? Thank you.

**Comment by lim-4158** [comment]
im not too sure about 3 but the main point about effect free functions is its 
1) deterministic output, which means given the same inputs, a pure function will always return the same output. 
2) the fact that it will not modify any external variable 

example: 
int add(int x, int y) { return x + y;} 
vs 
void addToList(int x, list y) { list.add(y); } 

eg1 is effect free because it doesnt mutate an external variable unlike eg2

hope this helped a little, the on lecture 9 explains this pretty well
feel free to add on or correct me if i am wrong

**Comment by zwz1707** [comment]
> im not too sure about 3 but the main point about effect free functions is its
> 
> 1. deterministic output, which means given the same inputs, a pure function will always return the same output.
> 2. the fact that it will not modify any external variable
> 
> example: int add(int x, int y) { return x + y;} vs void addToList(int x, list y) { list.add(y); }
> 
> eg1 is effect free because it doesnt mutate an external variable unlike eg2
> 
> hope this helped a little, the on lecture 9 explains this pretty well feel free to add on or correct me if i am wrong

It does, thank you!
