### ISSUE TITLE
when to use parallel()?

### ISSUE THREAD

**Issue by ndartem** [nus-cs2030/2324-s2#816]
hi when do we use parallel() and how does it work?

**Comment by ucantseemexr** [comment]
Hi, you can use parallel on complex computation involved stream to save time but the operation must be associative

**Comment by ZHD1987E** [comment]
In simple English: if your commands can work in ANY order (associative) then you call parallel() to do 'divide-and-conquer', making the streams faster (of course if you are doing trivial things don't because the 'divide-and-conquer' part ALSO takes time)

**Comment by thebestjiaozi** [comment]
I think it can be used in any order except for the terminating step?

**Comment by lifrocszh** [comment]
When you want to computations ansynchronously in streams, you ca do so by calling `.parralel()`, do take note that the computations need to be complex other wise you will spend more time forking and joining instead of computing, and that operations need to be associative in nature, meaning swapping the function arguments should not alter the result
