### ISSUE TITLE
ImList for Finals

### ISSUE THREAD

**Issue by HoSCD** [nus-cs2030/2324-s2#824]
Can ImList be used during finals? or can we only use List since ImList may not be provided.

**Comment by lifrocszh** [comment]
usually if it is required, they will provide, otherwise you probably need to use 1 or to static methods from List such as `List::of` for the conversion to something else such as `List.of(1,2,3).stream()`

if really needed, `ArrayList` is available, and functions exactly like an ImList without the immutability

**Comment by wangjiakng** [comment]
i think prof will provide ImList api, you can refer to mock paper on examplify. since we dont need to compile anything, its ok even if the qn doesnt provide implementation of ImList
