### ISSUE TITLE
Lecture 04 (Generic typing)

### ISSUE THREAD

**Issue by JosiahPraeman** [nus-cs2030/2324-s2#83]
# Description

Question: How do bounded type parameters contribute to the effectiveness of parametric polymorphism in Java?

## Topic:
Generic Typing

Specific Topics this question is related to (If Any)
Parametric polymorphism

**Comment by ZHD1987E** [comment]
If I create a Generic class that allows bounded type parameters, that means I am now able to use my code to be interoperable with more object types (so long they are a subclass of the superclass declared). And that makes trying to do parametric polymorphism much harder to do.

For example, with ImList<? extends Shape>, now I can add Circle and Rectangle into the same list, compared to having two (_tutututututututu_) ImList objects for each of the shape types. Moreover, with two ImLists that can cause further complications in source code down the line.

> PS: _tutututututututu_ is a Kurt Tay Gimmick when he mentions the number 2. He is going to Jill anyway so might as well commemorate him.

**Comment by hwkchia** [comment]
I think there are two separate issues here.

* parametric polymorphism lets an *implementer* define the same code for a class/interface that uses generic type parameters which can be bound to different types, e.g. defining `Comparator<T>` interface and binding `T` to `Integer`.
* bounded parameters lets the *client* of a generic class/interface allow for more general substitutions, i.e. rather than declaring a method to take in only a `Comparator<Integer>`, it can take in `Comparator<Integer>` or any comparator of its super-classes (such as `Comparator<Object>`) by using `Comparator<? super Integer>`.
