### ISSUE TITLE
when to use flatmap vs map

### ISSUE THREAD

**Issue by tarshalim** [nus-cs2030/2324-s2#833]
hi why do we use map instead of flatmap here? Is it because we are supposed to get Optional<PA> instead of PA, which is why we use map? in that case, why not use flatmap for the second map? thanks!

![image](https://github.com/nus-cs2030/2324-s2/assets/163754337/201cdae1-9ba5-40de-8ed2-330d6659ae30)

**Comment by grizzzle** [comment]
i think you're right that the first map is supposed to get a Optional<Integer>. for the second map, its aim is to map a PA to a Optional<Integer>, such that x will eventually become a Optional<Integer> from a optional<PA>. it wouldnt make sense to use flatmap for the second map since its not right to say that you flatten a PA into an optional<Integer>
this is my understanding, hope that helps!

**Comment by tarshalim** [comment]
ah i see thank you!
